import './assembly.css';
import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {buildMechanical} from './mechanical-models.js';
import {ASSEMBLY_VERSION,inspectAssembly,validPlacements,ISSUE_LABELS} from './assembly-state.js';
const $=s=>document.querySelector(s),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const KEY='auto-atlas.engine-assembly.v1',host=$('#canvas');
const renderer=new T.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.2;host.append(renderer.domElement);
const scene=new T.Scene(),camera=new T.PerspectiveCamera(37,1,.05,100),controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.minDistance=2;controls.maxDistance=30;
const pmrem=new T.PMREMGenerator(renderer),room=new RoomEnvironment();scene.environment=pmrem.fromScene(room,.03).texture;room.dispose();pmrem.dispose();scene.add(new T.HemisphereLight(0xf8fff9,0x759282,2));const light=new T.DirectionalLight(0xfff3de,3);light.position.set(4,7,6);scene.add(light);
const grid=new T.GridHelper(14,28,0xb8cdbd,0xd6e3d8);grid.position.y=-1;grid.material.transparent=true;grid.material.opacity=.45;scene.add(grid);
const model=buildMechanical('engine'),parts=model.parts,map=new Map(parts.map(p=>[p.userData.id,p]));scene.add(model.root);
const catalog=parts.map((p,i)=>({id:p.userData.id,name:p.userData.name,category:p.userData.category,number:i+1}));const ids=new Set(catalog.map(c=>c.id));
const localCenters=new Map(),slotCenters=new Map(),ghosts=new Map(),markers=new Map();const reference=new T.Group();scene.add(reference);
for(const p of parts){const d=p.userData;const center=new T.Box3().setFromObject(p).getCenter(new T.Vector3()).sub(d.base);localCenters.set(d.id,center);slotCenters.set(d.id,d.base.clone().add(center));
 const g=new T.Group();for(const source of p.children){if(!source.isMesh)continue;const m=new T.Mesh(source.geometry,new T.MeshBasicMaterial({color:0x8ba99a,transparent:true,opacity:.055,depthWrite:false,wireframe:true}));m.position.copy(source.position);m.quaternion.copy(source.quaternion);m.scale.copy(source.scale);g.add(m);}reference.add(g);ghosts.set(d.id,g);
 const dot=new T.Mesh(new T.SphereGeometry(.047,12,8),new T.MeshBasicMaterial({color:0x739e87,transparent:true,opacity:.7,depthTest:false}));dot.renderOrder=5;reference.add(dot);markers.set(d.id,dot);
 p.traverse(m=>{if(m.isMesh)m.material.userData.original={color:m.material.color.clone(),metalness:m.material.metalness,roughness:m.material.roughness};});
}
let placements={},attempts=[],selected='block',spread=.65,hints=false,hintedPart=null,hintUsage={allViews:0,parts:[]},historyId=null,storageBlocked=false,revision=0,undoStack=[],drag=null,candidate=null;
try{const saved=JSON.parse(localStorage.getItem(KEY)||'null');if(saved){if(saved.version!==ASSEMBLY_VERSION||!validPlacements(saved.placements,ids)||!Array.isArray(saved.attempts)||saved.attempts.some(a=>!a.id||typeof a.created!=='string'||!validPlacements(a.placements,ids)||typeof a.note!=='string'))throw Error('format');placements=saved.placements;attempts=saved.attempts;spread=Number.isFinite(saved.spread)?T.MathUtils.clamp(saved.spread,0,1):.65;if(saved.hintUsage&&Number.isInteger(saved.hintUsage.allViews)&&saved.hintUsage.allViews>=0&&Array.isArray(saved.hintUsage.parts)&&saved.hintUsage.parts.every(id=>ids.has(id)))hintUsage=saved.hintUsage;else if(saved.hints)hintUsage.allViews=1;}}catch{storageBlocked=true;$('#save-state').textContent='기록 읽기 실패 · 덮어쓰기 중지';}
$('#spread').value=spread*100;$('#spread-value').textContent=Math.round(spread*100)+'%';$('#hints').checked=hints;
function save(){if(storageBlocked)return false;try{localStorage.setItem(KEY,JSON.stringify({version:ASSEMBLY_VERSION,placements,attempts,spread,hints,hintUsage}));$('#save-state').textContent='이 브라우저에 자동 저장됨';return true;}catch{$('#save-state').textContent='저장 실패 · 기록을 내보내 주세요';return false;}}
function checkpoint(){undoStack.push(structuredClone(placements));if(undoStack.length>40)undoStack.shift();}
function changed(text){revision++;apply();renderList();renderDetail();save();$('#bench-message').textContent=text;}
function slotCenter(id){return slotCenters.get(id).clone().addScaledVector(map.get(id).userData.offset,spread);}
function groupCenter(id,p){return p.slot?slotCenter(p.slot):new T.Vector3(...p.position).addScaledVector(map.get(id).userData.offset,spread);}
function transformPart(id,center,rotation=[0,0,0]){const p=map.get(id);p.rotation.set(...rotation.map(T.MathUtils.degToRad));p.position.copy(center).sub(localCenters.get(id).clone().applyEuler(p.rotation));}
function apply(){for(const p of parts){const id=p.userData.id,placed=placements[id],chosen=id===selected;p.visible=!!placed;if(placed)transformPart(id,groupCenter(id,placed),placed.rotation);
 p.traverse(m=>{if(!m.isMesh)return;const b=m.material.userData.original;m.material.color.copy(b.color);m.material.emissive.set(chosen?0xba4329:0);m.material.emissiveIntensity=chosen?.25:0;if(chosen)m.material.color.set('#ee7956');const ghost=$('#shell').checked&&p.userData.shell;m.material.transparent=ghost;m.material.opacity=ghost?.22:1;m.material.depthWrite=!ghost;});
 const g=ghosts.get(id);g.position.copy(p.userData.base).addScaledVector(p.userData.offset,spread);g.visible=hints||hintedPart===id;g.traverse(m=>{if(m.isMesh){m.material.color.set(hintedPart===id?0xca8a49:0x8ba99a);m.material.opacity=hintedPart===id?.22:.045;}});
 const marker=markers.get(id);marker.position.copy(slotCenter(id));marker.visible=true;marker.material.color.set(candidate===id?0xe29142:0x65937b);marker.material.opacity=candidate===id?1:Object.values(placements).some(p=>p.slot===id)?.22:.62;marker.scale.setScalar(candidate===id?1.7:1);
 }model.root.updateMatrixWorld(true);reference.updateMatrixWorld(true);$('#inventory-count').textContent=`남은 ${parts.length-Object.keys(placements).length}`;$('#progress').textContent=`${Object.keys(placements).length} / ${parts.length} 배치`;$('#progress-bar').value=Object.keys(placements).length;$('#undo').disabled=!undoStack.length;$('#history-count').textContent=attempts.length;$('#hint-status').textContent=hintUsage.allViews||hintUsage.parts.length?`힌트 기록 · 전체 ${hintUsage.allViews}회 / 개별 ${hintUsage.parts.length}회`:'힌트 없이 도전 중 · 정답은 검사 후 확인';}
function select(id){candidate=null;hintedPart=null;selected=id;apply();renderList();renderDetail();}
function renderList(){const search=$('#search').value.trim().toLowerCase(),category=$('#category').value,availability=$('#availability').value;let html='';for(const cat of [...new Set(catalog.map(c=>c.category))]){const subset=catalog.filter(c=>c.category===cat&&(!category||category===cat)&&(`${c.name} ${map.get(c.id).userData.en}`.toLowerCase().includes(search))&&(!availability||(availability==='placed'?placements[c.id]:!placements[c.id])));if(!subset.length)continue;html+=`<div class="part-category">${esc(cat)} · ${subset.length}</div>`+subset.map(c=>`<div class="part-row ${placements[c.id]?'placed':''} ${selected===c.id?'selected':''}"><button draggable="true" data-part="${c.id}" aria-pressed="${selected===c.id}">${esc(c.name)}<small>${esc(map.get(c.id).userData.en)}</small></button><span>${placements[c.id]?'배치됨':'＋'}</span></div>`).join('');}$('#parts-list').innerHTML=html||'<p class="empty-parts">조건에 맞는 부품이 없습니다.</p>';
 $('#parts-list').querySelectorAll('[data-part]').forEach(b=>{b.onclick=()=>select(b.dataset.part);b.ondragstart=e=>{hintedPart=null;candidate=null;selected=b.dataset.part;e.dataTransfer.setData('application/x-auto-atlas-part',selected);e.dataTransfer.setData('text/plain',selected);e.dataTransfer.effectAllowed='move';drag={id:selected,native:true};apply();renderDetail();};b.ondragend=()=>{drag=null;candidate=null;$('#drop-label').hidden=true;apply();renderList();};});}
function renderDetail(){const p=map.get(selected),d=p.userData,placed=placements[selected];$('#part-detail').innerHTML=`<h2>${esc(d.name)}</h2><div class="english">${esc(d.en)}</div><div class="placement-state">${placed?(placed.slot?'자리 '+catalog.find(c=>c.id===placed.slot).number+'에 배치됨':'작업대에 임시 배치됨'):'보관함에 있는 부품'}</div><p>${esc(d.desc)}</p><div class="connection">연결 관계<br>${esc(d.connect)}</div><label class="slot-label" for="target-slot">조립 자리 선택 · 클릭 / 키보드 배치</label><select id="target-slot"><option value="">어느 자리에 놓을까요?</option>${catalog.map(c=>`<option value="${c.id}">${String(c.number).padStart(2,'0')} · ${esc(hints?c.name:'조립 자리')}</option>`).join('')}</select><button id="place-slot" class="primary" disabled>선택한 자리에 배치</button><div class="rotation-label">방향 ${placed?placed.rotation.join('° / ')+'°':'—'} · X / Y / Z</div><div class="rotation-buttons">${['X','Y','Z'].map((axis,i)=>`<button data-rotate="${i}" ${!placed?'disabled':''}>${axis} +90°</button>`).join('')}</div><div class="part-actions"><button id="return-part" ${!placed?'disabled':''}>보관함으로</button><button id="part-hint">이 부품 힌트 보기 · 기록됨</button><a href="/mechanics.html?system=engine&part=${encodeURIComponent(selected)}">이 부품 복습 ↗</a></div>`;
 $('#target-slot').onchange=e=>{$('#place-slot').disabled=!e.target.value;candidate=e.target.value||null;apply();};$('#place-slot').onclick=()=>place(selected,$('#target-slot').value);$('#return-part').onclick=()=>{checkpoint();delete placements[selected];changed('부품을 보관함으로 돌려놓았습니다.');};$('#part-hint').onclick=()=>{hintedPart=selected;hintUsage.parts.push(selected);candidate=selected;apply();$('#bench-message').textContent=`${d.name}의 자리만 표시했습니다. 힌트 사용이 기록됩니다. 부품을 직접 배치해보세요.`;save();};
 document.querySelectorAll('[data-rotate]').forEach(b=>b.onclick=()=>{checkpoint();placements[selected].rotation[+b.dataset.rotate]=(placements[selected].rotation[+b.dataset.rotate]+90)%360;changed('방향을 바꿨습니다. 검사에서 기준 방향을 확인할 수 있습니다.');});}
function place(id,slot,center=null){if(!ids.has(id)||slot&&!ids.has(slot))return;checkpoint();hintedPart=null;selected=id;placements[id]={slot:slot||null,position:(center||slotCenter(slot)).clone().addScaledVector(map.get(id).userData.offset,-spread).toArray(),rotation:placements[id]?.rotation||[0,0,0]};candidate=null;changed(slot?'부품을 조립 자리에 놓았습니다. 검사로 맞는 자리인지 확인해보세요.':'작업대에 놓았습니다. 원형 조립 자리로 옮겨 체결하세요.');}
const ray=new T.Raycaster(),mouse=new T.Vector2(),plane=new T.Plane(),dragPoint=new T.Vector3();
function coords(x,y){const r=host.getBoundingClientRect();mouse.set((x-r.left)/r.width*2-1,1-(y-r.top)/r.height*2);ray.setFromCamera(mouse,camera);return r;}
function hit(x,y){coords(x,y);return ray.intersectObjects(parts.filter(p=>p.visible),true).find(h=>h.object.userData.part)?.object.userData.part;}
function nearest(x,y){const r=host.getBoundingClientRect();let best=null,distance=hints?32:18;for(const c of catalog){const v=slotCenter(c.id).project(camera);if(v.z< -1||v.z>1)continue;const d=Math.hypot((v.x*.5+.5)*r.width+r.left-x,(.5-v.y*.5)*r.height+r.top-y);if(d<distance){distance=d;best=c.id;}}return best;}
function hoverDrag(x,y){candidate=nearest(x,y);coords(x,y);const center=ray.ray.intersectPlane(plane,dragPoint)?.clone();if(!center)return null;apply();const part=map.get(drag.id);part.visible=true;transformPart(drag.id,candidate?slotCenter(candidate):center,placements[drag.id]?.rotation);const label=$('#drop-label'),r=host.getBoundingClientRect();label.hidden=false;label.textContent=candidate?`자리 ${catalog.find(c=>c.id===candidate).number}${hints?' · '+map.get(candidate).userData.name:''} · 놓아서 배치`:'작업대에 임시 배치';label.style.left=Math.max(10,Math.min(x-r.left+10,host.clientWidth-220))+'px';label.style.top=(y-r.top+90)+'px';return center;}
function dragPlane(id){const center=placements[id]?groupCenter(id,placements[id]):new T.Vector3(0,2,0);plane.setFromNormalAndCoplanarPoint(camera.getWorldDirection(new T.Vector3()),center);}
host.ondragover=e=>{if(!drag?.native)return;e.preventDefault();e.dataTransfer.dropEffect='move';dragPlane(drag.id);hoverDrag(e.clientX,e.clientY);};host.ondragleave=e=>{if(host.contains(e.relatedTarget))return;candidate=null;$('#drop-label').hidden=true;apply();};host.ondrop=e=>{e.preventDefault();const id=e.dataTransfer.getData('application/x-auto-atlas-part');if(!ids.has(id)||!drag)return;const center=hoverDrag(e.clientX,e.clientY);if(center)place(id,candidate,center);drag=null;$('#drop-label').hidden=true;apply();};
renderer.domElement.addEventListener('pointerdown',e=>{if(e.button!==0)return;const p=hit(e.clientX,e.clientY);if(!p)return;select(p.userData.id);controls.enabled=false;drag={id:selected,x:e.clientX,y:e.clientY,moved:false};dragPlane(selected);renderer.domElement.setPointerCapture(e.pointerId);},true);
renderer.domElement.addEventListener('pointermove',e=>{if(!drag||drag.native)return;if(Math.hypot(e.clientX-drag.x,e.clientY-drag.y)>4)drag.moved=true;if(drag.moved)hoverDrag(e.clientX,e.clientY);});
function endPointer(e){if(!drag||drag.native)return;const d=drag;const r=host.getBoundingClientRect(),inside=e.clientX>=r.left&&e.clientX<=r.right&&e.clientY>=r.top&&e.clientY<=r.bottom;if(d.moved&&e.type!=='pointercancel'&&inside){const center=hoverDrag(e.clientX,e.clientY);if(center)place(d.id,candidate,center);}drag=null;candidate=null;controls.enabled=true;$('#drop-label').hidden=true;apply();}
renderer.domElement.addEventListener('pointerup',endPointer);renderer.domElement.addEventListener('pointercancel',endPointer);
function fit(direction=new T.Vector3(1.25,.8,1.6)){const box=new T.Box3();for(const g of ghosts.values())box.union(new T.Box3().setFromObject(g));const size=box.getSize(new T.Vector3()),center=box.getCenter(new T.Vector3());const radius=size.length()*.5,distance=radius/Math.sin(T.MathUtils.degToRad(camera.fov)*.5)*Math.max(1,1/camera.aspect)*.93;controls.target.copy(center);camera.position.copy(center).addScaledVector(direction.normalize(),distance);controls.update();}
function resize(){renderer.setSize(host.clientWidth,host.clientHeight);camera.aspect=host.clientWidth/host.clientHeight;camera.updateProjectionMatrix();fit();}new ResizeObserver(resize).observe(host);
$('#view-home').onclick=()=>fit();$('#view-front').onclick=()=>fit(new T.Vector3(0,.06,1));$('#view-top').onclick=()=>fit(new T.Vector3(0,1,.001));$('#view-side').onclick=()=>fit(new T.Vector3(1,.06,0));$('#spread').oninput=e=>{spread=+e.target.value/100;$('#spread-value').textContent=Math.round(spread*100)+'%';apply();save();};$('#hints').onchange=e=>{hints=e.target.checked;hintedPart=null;candidate=null;if(hints)hintUsage.allViews++;apply();renderDetail();save();};$('#shell').onchange=apply;
$('#category').innerHTML+=[...new Set(catalog.map(c=>c.category))].map(c=>`<option>${esc(c)}</option>`).join('');for(const id of ['#search','#category','#availability'])$(id).oninput=renderList;
$('#undo').onclick=()=>{if(!undoStack.length)return;placements=undoStack.pop();changed('직전 조립 동작을 되돌렸습니다.');};$('#restart').onclick=()=>$('#restart-confirm').hidden=false;$('#restart-no').onclick=()=>$('#restart-confirm').hidden=true;$('#restart-yes').onclick=()=>{undoStack=[];placements={};hints=false;hintedPart=null;candidate=null;hintUsage={allViews:0,parts:[]};$('#hints').checked=false;$('#restart-confirm').hidden=true;changed('새 조립을 시작합니다. 기존 검사 기록은 유지됩니다.');};
function date(s){return new Date(s).toLocaleString('ko-KR',{dateStyle:'short',timeStyle:'short'});}
function renderHistory(){const list=$('#history-list');list.innerHTML=attempts.length?[...attempts].reverse().map((a,i)=>{const r=inspectAssembly(catalog,a.placements);return `<button class="history-item ${historyId===a.id?'active':''}" data-attempt="${a.id}"><small>${attempts.length-i}회 · ${date(a.created)}</small><b>${r.passed?'조립 완료':r.score+'점 · 다시 살펴보기'}</b><span>정확 ${r.correct} · 누락 ${r.missing} · 오류 ${r.incorrect}</span></button>`;}).join(''):'<p class="muted">아직 검사 기록이 없습니다.</p>';list.querySelectorAll('button').forEach(b=>b.onclick=()=>showReport(b.dataset.attempt));}
function showReport(id){historyId=id;$('#report').scrollTop=0;const a=attempts.find(a=>a.id===id);renderHistory();if(!a){$('#report').innerHTML='<div id="history-empty">직접 조립한 뒤 검사받기를 눌러보세요.<br>빠진 부품과 잘못된 배치를 기록합니다.</div>';return;}const r=inspectAssembly(catalog,a.placements),different=JSON.stringify(a.placements)!==JSON.stringify(placements);$('#report').innerHTML=`<span class="eyebrow">${date(a.created)} · 검사 당시 상태</span><div class="report-score">${r.score}<small> / 100</small></div><h2>${r.passed?'80개 부품의 자리와 방향을 맞췄습니다.':'아직 조립할 부분이 남아 있습니다.'}</h2><p class="report-summary">정확 ${r.correct}개 · 빠진 부품 ${r.missing}개 · 배치·방향 오류 ${r.incorrect}개</p>${different?'<p class="report-warning">현재 작업대와 다른 검사 기록입니다. 수정한 조립은 다시 검사해주세요.</p>':''}<p class="report-label">${a.hintUsage?`힌트 기록 · 전체 ${a.hintUsage.allViews}회 / 개별 ${a.hintUsage.parts.length}회`:`기존 기록 · 검사 시 힌트 ${a.hints?'켜짐':'꺼짐'}`} · 번호별 기준 자리·방향 검사</p><div class="report-actions"><button id="resume-attempt">이 검사 상태에서 다시 조립</button><button id="continue-work">현재 작업대로 돌아가기</button></div><div id="resume-confirm" hidden class="report-warning">현재 작업대를 이 검사 당시 상태로 바꿀까요? <button id="resume-yes">불러오기</button><button id="resume-no">취소</button></div>${[['빠진 부품',r.results.filter(x=>x.issues.includes('missing'))],['잘못 배치한 부품',r.results.filter(x=>x.issues.length&&!x.issues.includes('missing'))],['정확하게 배치한 부품',r.results.filter(x=>!x.issues.length)]].map(([label,rows],index)=>`<details class="report-group" ${index<2&&rows.length?'open':''}><summary>${label} · ${rows.length}</summary>${rows.map(x=>`<div class="issue-row"><span>${esc(x.name)}<small>${x.issues.map(k=>ISSUE_LABELS[k]).join(' · ')||'기준 자리·방향 일치'}${x.slot&&x.slot!==x.id?' · 현재: '+esc(map.get(x.slot).userData.name)+' 자리':''}</small></span><button data-review="${x.id}">부품 살펴보기</button></div>`).join('')}</details>`).join('')}<label class="report-note">이번 실습에서 배운 점 · 다음에 확인할 것<textarea id="attempt-note" maxlength="12000" placeholder="예: 2번 피스톤의 오일 링을 빠뜨렸다. 압축 링과 역할을 다시 확인하기.">${esc(a.note)}</textarea></label><span id="note-state">메모는 입력할 때 자동 저장됩니다.</span>`;
 $('#attempt-note').oninput=e=>{a.note=e.target.value;$('#note-state').textContent=save()?'메모 저장됨':'메모 저장 실패 · 기록을 내보내 주세요';};$('#continue-work').onclick=()=>$('#history').close();$('#resume-attempt').onclick=()=>$('#resume-confirm').hidden=false;$('#resume-no').onclick=()=>$('#resume-confirm').hidden=true;$('#resume-yes').onclick=()=>{checkpoint();placements=structuredClone(a.placements);hints=false;hintedPart=null;candidate=null;$('#hints').checked=false;if(a.hintUsage){hintUsage.allViews+=a.hintUsage.allViews;hintUsage.parts.push(...a.hintUsage.parts);}else if(a.hints)hintUsage.allViews++;changed('검사 당시 상태를 불러왔습니다. 고친 뒤 새 검사를 남겨보세요.');$('#history').close();};document.querySelectorAll('[data-review]').forEach(b=>b.onclick=()=>{select(b.dataset.review);$('#search').value='';$('#category').value='';$('#availability').value='';renderList();$('#history').close();$('#bench-message').textContent='부품을 선택했습니다. 자리 힌트나 부품 복습으로 확인해보세요.';});}
$('#check').onclick=()=>{const a={id:crypto.randomUUID(),created:new Date().toISOString(),placements:structuredClone(placements),hints,hintUsage:structuredClone(hintUsage),note:''};attempts.push(a);const saved=save();apply();showReport(a.id);if(!saved){const warning=document.createElement('p');warning.className='report-warning';warning.textContent='이 검사 기록을 브라우저에 저장하지 못했습니다. 기록 내보내기로 보관해주세요.';$('#report').prepend(warning);}$('#history').showModal();};$('#history-open').onclick=()=>{showReport(historyId||attempts.at(-1)?.id);$('#history').showModal();};$('#history-close').onclick=()=>$('#history').close();
$('#export-history').onclick=()=>{const blob=new Blob([JSON.stringify({version:ASSEMBLY_VERSION,exported:new Date().toISOString(),catalog,placements,attempts:attempts.map(a=>({...a,assessment:inspectAssembly(catalog,a.placements)}))},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='engine-assembly-history-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
apply();renderList();renderDetail();resize();if(!storageBlocked)$('#save-state').textContent=Object.keys(placements).length?'지난 조립을 이어서 진행합니다.':'변경하면 자동 저장됩니다.';
function frame(){requestAnimationFrame(frame);controls.update();renderer.render(scene,camera);}frame();
window.__assembly={parts,catalog,camera,renderer,getState:()=>({placements:structuredClone(placements),attempts:structuredClone(attempts),selected,spread,hints,hintedPart,hintUsage:structuredClone(hintUsage),visibleReferences:[...ghosts].filter(([,g])=>g.visible).map(([id])=>id),revision}),inspect:()=>inspectAssembly(catalog,placements),slotScreen:id=>{const v=slotCenter(id).project(camera),r=host.getBoundingClientRect();return {x:r.left+(v.x*.5+.5)*r.width,y:r.top+(.5-v.y*.5)*r.height};}};
