import * as T from 'three';
import {buildMechanical} from './mechanical-models.js';
import {RoundedBoxGeometry} from 'three/addons/geometries/RoundedBoxGeometry.js';
export function buildDrivetrain(){const root=new T.Group(),parts=[];let g;
 const mats={steel:['#b8c6ce',.78,.3],dark:['#354753',.55,.43],rubber:['#28343a',.03,.8],teal:['#339888',.45,.38],bronze:['#b99358',.65,.4]};
 function part(id,name,cat,pos,off,why,together,without,related,shell=false){g=new T.Group();g.position.set(...pos);g.userData={id,name,en:'Functional drivetrain reference',category:cat,base:new T.Vector3(...pos),offset:new T.Vector3(...off),color:'#709f9b',desc:why,connect:together,shell,education:{why,together,without,related:related.split(' ')}};parts.push(g);root.add(g);return g;}
 function mesh(geo,key='steel',pos=[0,0,0],rot=[0,0,0]){const [color,metalness,roughness]=mats[key];const m=new T.Mesh(geo,new T.MeshStandardMaterial({color,metalness,roughness}));m.position.set(...pos);m.rotation.set(...rot);g.add(m);return m;}
 function box(w,h,d,key='steel',pos=[0,0,0]){return mesh(new RoundedBoxGeometry(w,h,d,2,.025),key,pos);}
 function cyl(r,h,key='steel',pos=[0,0,0],axis='x'){return mesh(new T.CylinderGeometry(r,r,h,40),key,pos,axis==='x'?[0,0,Math.PI/2]:axis==='z'?[Math.PI/2,0,0]:[0,0,0]);}
 function ring(r,t,key='steel',pos=[0,0,0],axis='x'){return mesh(new T.TorusGeometry(r,t,8,48),key,pos,axis==='x'?[0,Math.PI/2,0]:axis==='y'?[Math.PI/2,0,0]:[0,0,0]);}
 function sleeve(r,ri,h,key='steel',pos=[0,0,0],axis='x'){return mesh(new T.LatheGeometry([[ri,-h/2],[r,-h/2],[r,h/2],[ri,h/2],[ri,-h/2]].map(p=>new T.Vector2(...p)),40),key,pos,axis==='x'?[0,0,Math.PI/2]:axis==='z'?[Math.PI/2,0,0]:[0,0,0]);}
 function gear(r,n,w=.08,key='steel'){sleeve(r-.015,.065,w,key);for(let i=0;i<n;i++){let a=i*Math.PI*2/n;const m=box(w,.052,.032,key,[0,r*Math.cos(a),r*Math.sin(a)]);m.rotation.x=a;}}
 function link(a,b,r=.035,key='steel'){const av=new T.Vector3(...a),bv=new T.Vector3(...b),m=cyl(r,av.distanceTo(bv),key,av.clone().add(bv).multiplyScalar(.5).toArray(),'y');m.quaternion.setFromUnitVectors(new T.Vector3(0,1,0),bv.sub(av).normalize());}
 const cc='클러치 · 연결';
 part('drive-flywheel','엔진측 플라이휠',cc,[-2.25,1.3,-1.35],[-.9,0,0],'엔진의 회전 관성을 제공하고 클러치의 마찰면을 지지합니다.','플라이휠과 압력판이 마찰판을 누르면 입력축으로 토크가 전달됩니다.','클러치 입력측 지지와 관성이 없어집니다.','friction-disc pressure-plate');gear(.38,40,.12);
 part('friction-disc','클러치 마찰판 · 댐퍼 스프링',cc,[-2.08,1.3,-1.35],[-.5,0,.6],'마찰로 엔진 회전을 입력축에 연결합니다.','마찰 라이닝은 양쪽 면과 접촉하고 중앙 스플라인은 입력축에 연결됩니다.','회전력을 마찰로 전달하기 어렵습니다.','drive-flywheel pressure-plate input-shaft');sleeve(.31,.14,.045,'dark');sleeve(.15,.055,.1);for(let i=0;i<6;i++){const a=i*Math.PI/3;cyl(.027,.1,'bronze',[0,.11*Math.cos(a),.11*Math.sin(a)],'y');}
 part('pressure-plate','클러치 압력판',cc,[-1.95,1.3,-1.35],[-.1,.2,.6],'마찰판을 플라이휠 쪽으로 누릅니다.','다이어프램 스프링의 힘을 받아 회전 중에도 축 방향 누름을 제공합니다.','마찰판에 충분한 누름 힘을 주기 어렵습니다.','friction-disc diaphragm');sleeve(.34,.11,.08);
 part('diaphragm','다이어프램 스프링',cc,[-1.84,1.3,-1.35],[.1,.7,0],'압력판에 누름 힘을 주고 분리 동작을 전달합니다.','분리 베어링이 안쪽 핑거를 밀어 압력판의 누름을 풉니다.','클러치의 연결·분리를 조절하기 어렵습니다.','pressure-plate release-bearing');sleeve(.3,.19,.025,'dark');for(let i=0;i<18;i++){const a=i*Math.PI/9;const m=box(.025,.15,.018,'dark',[0,.14*Math.cos(a),.14*Math.sin(a)]);m.rotation.x=a;}
 part('release-bearing','클러치 분리 베어링',cc,[-1.68,1.3,-1.35],[.4,.3,.4],'회전하는 다이어프램에 축 방향 분리력을 전달합니다.','정지측 액추에이터와 회전측 스프링 사이 상대 회전을 허용합니다.','분리력 전달과 회전 마찰 관리가 나빠집니다.','diaphragm');sleeve(.115,.065,.08,'bronze');
 part('clutch-cover','클러치 커버',cc,[-1.87,1.3,-1.35],[0,1,-.3],'압력판과 스프링을 회전 조립체 안에 지지합니다.','플라이휠 측 체결부와 압력판을 구조적으로 이어 줍니다.','누름 계통의 구조 지지를 잃습니다.','drive-flywheel pressure-plate diaphragm',true);sleeve(.38,.32,.25,'dark');
 const gg='기어 · 변속';
 part('input-shaft','변속기 입력축',gg,[-.72,1.3,-1.35],[0,.3,-.5],'클러치에서 받은 회전을 입력 기어로 전달합니다.','마찰판의 스플라인과 기어 사이에서 비틀림 하중을 전달합니다.','입력 기어에 회전력을 전달할 수 없습니다.','friction-disc input-gear bearing-in');cyl(.06,2.2);for(let i=0;i<10;i++)ring(.064,.008,'dark',[-.85+i*.025,0,0]);
 part('input-gear','입력 기어 · 20개 이',gg,[.3,1.3,-1.35],[.4,.65,0],'출력 기어를 이의 맞물림으로 구동합니다.','40개 이의 출력 기어를 구동하면 출력은 반대 방향·절반 속도로 회전합니다.','맞물림으로 토크를 전달할 수 없습니다.','input-shaft output-gear');gear(.2,20);
 part('output-gear','출력 기어 · 40개 이',gg,[.3,.7,-1.35],[.4,-.45,0],'더 큰 이 수로 속도를 줄이고 토크 비를 바꿉니다.','20:40 외접 기어쌍은 이상적으로 2:1 감속합니다. 이 모델은 한 단의 기어쌍입니다.','의도한 감속비를 얻지 못합니다.','input-gear output-shaft');gear(.4,40,.1,'teal');
 part('output-shaft','출력축',gg,[.25,.7,-1.35],[.8,-.3,-.4],'기어의 회전을 종감속·차동기어 쪽으로 전달합니다.','다음 장치까지 이어지는 경로는 기능 흐름선으로 표시합니다. 실제 포장 배치는 다릅니다.','변속 출력이 구동축으로 전달되지 않습니다.','output-gear diff-ring bearing-out');cyl(.065,1.6);
 for(const [id,y]of [['bearing-in',1.3],['bearing-out',.7]]){part(id,(id==='bearing-in'?'입력':'출력')+'축 베어링',gg,[-.2,y,-1.35],[-.3,id==='bearing-in'?.5:-.5,0],'회전축의 위치와 하중을 지지합니다.','내륜과 외륜 사이 전동체가 상대 회전을 허용합니다.','축 정렬과 원활한 회전이 나빠집니다.','input-shaft output-shaft');sleeve(.13,.085,.08);for(let i=0;i<12;i++){const a=i*Math.PI/6;mesh(new T.SphereGeometry(.018,10,8),'steel',[0,.1*Math.cos(a),.1*Math.sin(a)]);}}
 part('selector','선택 슬리브 · 포크 참고',gg,[.6,.7,-1.35],[.7,0,.4],'선택한 기어를 축에 연결하는 변속 장치의 역할을 나타냅니다.','여기서는 고정된 한 기어쌍만 구동하며 싱크로나이저 마찰·변속 과정은 생략합니다.','원하는 기어 경로를 선택하기 어렵습니다.','output-gear output-shaft');sleeve(.11,.07,.12,'bronze');link([0,0,.13],[0,.25,.13],.022);
 part('gearbox-case','변속기 하우징',gg,[.05,1,-1.35],[0,.5,-.9],'축과 베어링 위치를 고정하고 윤활 공간을 둘러쌉니다.','입력·출력축 베어링을 통해 전달되는 하중을 지지합니다.','정렬·윤활·하중 지지가 나빠집니다.','bearing-in bearing-out',true);box(1.3,.05,.9,'dark',[0,-.53,0]);for(const z of [-.43,.43])box(1.3,1.05,.04,'dark',[0,0,z]);
 const dd='차동 · 구동축';
 part('diff-case','차동기어 케이스',dd,[0,.8,.8],[0,.2,-.6],'종감속에서 받은 회전을 좌우 기어로 전달하는 회전 틀입니다.','오픈 디퍼렌셜에서 케이스 속도는 좌우 축 속도의 평균입니다. e-LSD는 재현하지 않습니다.','좌우 기어 지지와 회전 전달을 잃습니다.','diff-ring side-left side-right spider',true);sleeve(.34,.28,.55,'dark');
 part('diff-ring','종감속 링 기어',dd,[-.28,.8,.8],[-.5,0,0],'변속기 출력의 회전을 차동기어 케이스로 전달합니다.','실제 최종 감속 피니언의 배치는 생략하고 기능 경로로 연결했습니다.','차동기어에 구동 회전을 전달하기 어렵습니다.','output-shaft diff-case');gear(.38,40,.07,'teal');
 for(const [id,x]of [['side-left',-.18],['side-right',.18]]){part(id,(x<0?'왼쪽':'오른쪽')+' 사이드 기어',dd,[x,.8,.8],[x<0?-.4:.4,.35,0],'각 구동축에 연결되어 좌우 속도 차를 허용합니다.','스파이더 기어와 맞물려 한쪽이 빨라지면 다른 쪽은 평균 대비 느려집니다.','좌우 차륜으로 차동 회전을 전달하기 어렵습니다.','spider diff-case '+(x<0?'axle-left':'axle-right'));gear(.16,16,.065,'bronze');}
 part('spider','스파이더 기어 · 크로스 핀',dd,[0,.8,.8],[0,.65,.2],'케이스와 함께 공전하며 필요할 때 자전해 좌우 속도 차를 만듭니다.','기어 치형은 개념 형상입니다. 시연은 좌우 평균 속도 관계를 맞춘 이상 모델입니다.','커브에서 좌우 회전 차를 수용하기 어렵습니다.','side-left side-right diff-case');cyl(.025,.47,'steel',[0,0,0],'y');for(const y of [-.18,.18]){mesh(new T.ConeGeometry(.12,.07,16),'steel',[0,y,0],[y<0?Math.PI:0,0,0]);}
 for(const [side,sign]of [['left',-1],['right',1]]){
 part('axle-'+side,(sign<0?'왼쪽':'오른쪽')+' 반축',dd,[sign*1.25,.8,.8],[sign*.6,-.4,0],'차동기어의 토크를 휠측 조인트로 전달합니다.','사이드 기어와 CV 조인트를 회전축으로 잇습니다.','해당 차륜으로 토크를 전달하기 어렵습니다.','side-'+side+' cv-'+side);cyl(.043,1.9);
 part('cv-'+side,(sign<0?'왼쪽':'오른쪽')+' CV 조인트',dd,[sign*2.2,.8,.8],[sign*.5,.4,.4],'휠의 조향각이 변해도 회전력을 전달하도록 관절을 제공합니다.','부트가 내부 그리스·관절을 보호합니다. 볼 트랙 내부 운동은 생략했습니다.','각도가 있는 상태의 회전력 전달이 나빠집니다.','axle-'+side+' wheel-'+side);cyl(.12,.17);for(let i=0;i<6;i++)ring(.11-i*.009,.015,'rubber',[sign*(-.15-i*.04),0,0]);
 part('wheel-'+side,(sign<0?'왼쪽':'오른쪽')+' 휠 · 타이어','휠 · 접지',[sign*2.5,.8,.8],[sign*.7,0,.65],'축 토크를 노면 접선력으로 바꾸는 접촉 부위입니다.','타이어가 노면을 뒤로 미는 힘에 대한 반력이 차량을 앞으로 가속합니다. 접지 한계가 있습니다.','구동·제동·횡력 전달에 필요한 접촉을 잃습니다.','cv-'+side+' steer-'+side);sleeve(.59,.4,.3,'rubber');sleeve(.395,.34,.29);cyl(.12,.32);for(let i=0;i<8;i++){const a=i*Math.PI/4;const m=box(.1,.27,.045,'steel',[0,.22*Math.cos(a),.22*Math.sin(a)]);m.rotation.x=a;}for(let i=0;i<44;i++){const a=i*Math.PI*2/44;const m=box(.28,.018,.036,'dark',[0,.59*Math.cos(a),.59*Math.sin(a)]);m.rotation.x=a;}
 }
 const ss='조향 · 링크';
 part('steering-wheel','스티어링 휠',ss,[-1.1,1.8,1.9],[-.4,.7,.5],'운전자의 회전 입력을 조향계에 전달합니다.','컬럼이 회전을 피니언으로 보냅니다. 손잡이 회전과 바퀴 조향각은 같지 않습니다.','조향 입력을 전달하기 어렵습니다.','steering-column');ring(.3,.035,'rubber',[0,0,0],'z');cyl(.08,.1,'dark',[0,0,0],'z');for(const x of [-.24,.24])link([0,0,0],[x,-.1,0],.025);
 part('steering-column','조향 컬럼 · 유니버설 조인트',ss,[-1.1,1.4,1.55],[-.4,.4,.6],'핸들의 회전을 랙 장치로 전달합니다.','실제 컬럼 경로는 차량 포장에 따라 달라집니다. 기능 배치를 사용했습니다.','피니언으로 회전 입력을 전달하기 어렵습니다.','steering-wheel pinion');link([0,.4,.35],[0,-.4,-.3],.035);link([0,-.4,-.3],[1.1,-.71,-.05],.035);mesh(new T.SphereGeometry(.063,14,10),'steel',[0,-.4,-.3]);
 part('pinion','조향 피니언',ss,[0,.69,1.5],[0,.4,.6],'회전하여 랙을 직선으로 움직입니다.','피니언 유효 반지름과 랙 이동의 관계를 맞춘 개념 기어입니다.','회전을 랙 이동으로 변환하기 어렵습니다.','rack steering-column');const pin=g;gear(.1,16,.1);pin.children.forEach(m=>{m.position.applyAxisAngle(new T.Vector3(0,1,0),Math.PI/2);m.quaternion.premultiply(new T.Quaternion().setFromAxisAngle(new T.Vector3(0,1,0),Math.PI/2));});
 part('rack','조향 랙 · 치형 바',ss,[0,.55,1.5],[0,-.35,.7],'피니언 회전을 좌우 직선 이동으로 바꿉니다.','양 끝 타이로드가 좌우 너클에 입력을 전달합니다.','타이로드에 조향 변위를 줄 수 없습니다.','pinion tie-left tie-right');box(2.4,.07,.085);for(let i=0;i<20;i++)box(.025,.03,.085,'steel',[-.4+i*.042,.05,0]);
 part('rack-case','랙 하우징 · 부트',ss,[0,.55,1.5],[0,-.65,.3],'랙을 지지하고 회전·직선 운동부를 이물질로부터 보호합니다.','양 끝의 부트는 랙 이동을 수용합니다.','랙 안내와 윤활·방진 유지가 나빠집니다.','rack pinion',true);sleeve(.12,.08,1.55,'dark');for(const x of [-.9,.9])for(let i=0;i<5;i++)ring(.11,.018,'rubber',[x+(x<0?-1:1)*i*.05,0,0]);
 part('eps-motor','EPS 보조 모터',ss,[.7,.8,1.5],[.5,.5,.5],'운전자 입력과 주행 상태에 맞춰 조향력을 보조합니다.','센서·ECU 제어는 설명만 하며 실제 모터 제어와 기어 감속은 해석하지 않습니다.','수동 기계 연결과 별개로 보조 토크가 줄어들 수 있습니다.','rack pinion');cyl(.13,.35,'dark');
 for(const [side,sign]of [['left',-1],['right',1]]){
 part('tie-'+side,(sign<0?'왼쪽':'오른쪽')+' 타이로드',ss,[0,0,0],[sign*.3,-.3,.8],'랙의 직선 이동을 너클의 회전에 연결합니다.','양 끝 볼 조인트가 각도 변화를 허용하고 링크 길이는 일정합니다.','너클에 조향 입력을 전달하기 어렵습니다.','rack steer-'+side);link([sign*1.2,.55,1.5],[sign*2.5,.8,1.12]);
 part('steer-'+side,(sign<0?'왼쪽':'오른쪽')+' 조향 너클 · 암',ss,[sign*2.5,.8,.8],[sign*.3,.3,.3],'타이로드 힘을 받아 휠 축의 방향을 바꿉니다.','이 참고 모델은 수직 조향축과 평면 링크를 사용합니다. 실제 캐스터·캠버는 생략합니다.','휠의 방향과 링크 하중을 지지하기 어렵습니다.','tie-'+side+' wheel-'+side);cyl(.1,.3);link([0,0,0],[0,0,.32],.055);
 }
 part('source-engine','동력원 · 직렬 4기통 엔진','엔진 · 동력원',[-3,1.092,-1.35],[-.8,.5,0],'연소 압력을 회전력으로 바꾸는 기존 엔진 상세 모델입니다.','피스톤·로드·크랭크축이 만든 회전을 플라이휠과 클러치로 전달합니다.','구동계에 공급할 엔진 출력이 없어집니다.','drive-flywheel friction-disc');
 const engine=buildMechanical('engine');engine.root.scale.setScalar(.32);for(const p of engine.parts)if(['block','head','cover','pan','pickup','flywheel'].includes(p.userData.id))p.visible=false;g.add(engine.root);g.userData.engineModel=engine;g.userData.drill='engine';
 root.updateMatrixWorld(true);for(const p of parts)p.traverse(m=>{if(m.isMesh)m.userData.part=p;});return {root,parts};}
