import {installQuestions} from './questions.js';
import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {connectedComponents} from './components.js';
import {catalog,classify,MODEL_SOURCE} from './part-catalog.js';
import {vehicleLearning} from './vehicle-learning.js';
const $=s=>document.querySelector(s),host=$('#canvas');
const scene=new THREE.Scene();let renderer;
try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,preserveDrawingBuffer:true});}catch(e){$('#loading').innerHTML='<b>WebGL을 사용할 수 없습니다.</b><span>Chrome의 하드웨어 가속을 켜고 다시 열어주세요.</span>';throw e;}
renderer.setPixelRatio(Math.min(devicePixelRatio,1.8));renderer.setClearColor(0x000000,0);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;renderer.localClippingEnabled=true;host.appendChild(renderer.domElement);
const camera=new THREE.PerspectiveCamera(34,1,.05,100);camera.position.set(6,3.6,6.5);
const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,.65,0);controls.enableDamping=true;controls.minDistance=.3;controls.maxDistance=25;controls.maxPolarAngle=Math.PI*.95;controls.autoRotateSpeed=.6;
const envGenerator=new THREE.PMREMGenerator(renderer),room=new RoomEnvironment();scene.environment=envGenerator.fromScene(room,.04).texture;room.dispose();envGenerator.dispose();scene.add(new THREE.HemisphereLight(0xeaf6ff,0x879caf,1.9));
const key=new THREE.DirectionalLight(0xfff6e9,3);key.position.set(2,6,4);key.castShadow=true;key.shadow.mapSize.set(2048,2048);Object.assign(key.shadow.camera,{left:-7,right:7,top:7,bottom:-7});key.shadow.normalBias=.012;scene.add(key);const fill=new THREE.DirectionalLight(0xe0f1ff,1.5);fill.position.set(-3,3,-4);scene.add(fill);
const ground=new THREE.Mesh(new THREE.PlaneGeometry(200,200),new THREE.ShadowMaterial({opacity:.16}));ground.rotation.x=-Math.PI/2;ground.position.y=-.055;ground.receiveShadow=true;scene.add(ground);const grid=new THREE.GridHelper(16,32,0xcbd9df,0xe0e8eb);grid.position.y=-.052;grid.material.transparent=true;grid.material.opacity=.32;scene.add(grid);
const car=new THREE.Group();scene.add(car);const groups={},meshes=[],data=[],localCenters={},bounds={};let allSelected=false,selectionSnapshot=null,selected='body',explosion=0,targetExplosion=0,transparent=false,solo=null,category='전체',ready=false,openAmount={hood:0,doors:0,trunk:0},sourceTriangles=0,visibleTriangles=0;
const pivots={hood:new THREE.Vector3(1.015,.915,0),trunk:new THREE.Vector3(-1.94,.99,0)};for(const p of ['fl','fr','rl','rr'])pivots['door-'+p]=new THREE.Vector3(p[0]==='f'?.88:-.25,.56,p[1]==='l'?-.82:.82);
for(const d of catalog){const g=new THREE.Group();g.userData={id:d.id,pivot:pivots[d.id]||new THREE.Vector3(),offset:new THREE.Vector3(...d.offset),triangles:0,sourceNodes:new Set()};g.position.copy(g.userData.pivot);groups[d.id]=g;car.add(g);}
const cutPlane=new THREE.Plane(new THREE.Vector3(0,0,-1),0);
function compactGeometry(source,indices,pivot){const remap=new Map(),unique=[],ix=new Uint32Array(indices.length);indices.forEach((old,i)=>{if(!remap.has(old)){remap.set(old,unique.length);unique.push(old);}ix[i]=remap.get(old);});const geo=new THREE.BufferGeometry();for(const [name,attr]of Object.entries(source.attributes)){const out=new attr.array.constructor(unique.length*attr.itemSize);for(let i=0;i<unique.length;i++)for(let k=0;k<attr.itemSize;k++)out[i*attr.itemSize+k]=attr.array[unique[i]*attr.itemSize+k];geo.setAttribute(name,new THREE.BufferAttribute(out,attr.itemSize,attr.normalized));}geo.setIndex(new THREE.BufferAttribute(ix,1));geo.translate(-pivot.x,-pivot.y,-pivot.z);geo.computeBoundingBox();geo.computeBoundingSphere();return geo;}
async function load(){try{
 const gltf=await new GLTFLoader().loadAsync('/models/elantra-n.glb',e=>{$('#load-progress').textContent=e.total?`파일 다운로드 ${Math.round(e.loaded/e.total*100)}%`:'상세 형상을 내려받고 있습니다…';});
 $('#load-progress').textContent='원본 형상을 부품별로 정리하고 있습니다…';await new Promise(r=>setTimeout(r,20));
 gltf.scene.scale.setScalar(100);gltf.scene.rotation.y=Math.PI/2;gltf.scene.updateMatrixWorld(true);const originals=[];gltf.scene.traverse(o=>{if(o.isMesh)originals.push(o);});
 for(const original of originals){const geo=original.geometry.clone();geo.applyMatrix4(original.matrixWorld);if(original.matrixWorld.determinant()<0){const a=geo.index.array;for(let i=0;i<a.length;i+=3)[a[i+1],a[i+2]]=[a[i+2],a[i+1]];}
 sourceTriangles+=geo.index.count/3;const pieces=connectedComponents(geo,false),buckets=new Map();for(const piece of pieces){const id=classify(original.name+' '+original.material.name,piece);if(!buckets.has(id))buckets.set(id,[]);for(const i of piece.indices)buckets.get(id).push(i);}
 for(const [id,indices]of buckets){const g=groups[id],material=original.material.clone();material.side=THREE.DoubleSide;material.envMapIntensity=1.15;
 if(/Paint_Material/.test(material.name)){material.color.set('#9bc5d6');material.metalness=.55;material.roughness=.27;material.clearcoat=.6;}
 if(material.transmission!==undefined)material.transmission=0; // Screen-space transmission obscures hidden/exploded parts.
 if(/Window/.test(material.name)&&!material.name.includes('red_glass')){material.opacity=.27;material.transparent=true;material.depthWrite=false;material.roughness=.12;material.metalness=.1;}
 material.userData.base={color:material.color.clone(),metalness:material.metalness,roughness:material.roughness,opacity:material.opacity,transparent:material.transparent,depthWrite:material.depthWrite,emissive:material.emissive.clone(),intensity:material.emissiveIntensity};
 const m=new THREE.Mesh(compactGeometry(geo,indices,g.userData.pivot),material);m.name=original.name;m.userData={id,sourceName:original.name};m.castShadow=!/Window/.test(material.name);m.receiveShadow=true;g.add(m);meshes.push(m);g.userData.triangles+=indices.length/3;g.userData.sourceNodes.add(original.name);}
 geo.dispose();await new Promise(r=>setTimeout(r,0));
 }
 for(const d of catalog){const g=groups[d.id];if(!g.children.length){car.remove(g);delete groups[d.id];continue;}data.push(d);const box=new THREE.Box3();for(const m of g.children)box.union(m.geometry.boundingBox);bounds[d.id]=box;localCenters[d.id]=box.getCenter(new THREE.Vector3());}
 const total=data.reduce((n,d)=>n+groups[d.id].userData.triangles,0);if(total!==sourceTriangles)throw Error('원본 삼각형 수 보존 검증 실패');
 $('#assembly-count').textContent=data.length;$('#loading').remove();ready=true;select(groups[new URLSearchParams(location.search).get('part')]?new URLSearchParams(location.search).get('part'):'body');view('perspective');createLabels();updateStatus();window.__atlas={scene,camera,groups,data,renderer,sourceTriangles,getState:()=>({allSelected,selected,explosion,targetExplosion,transparent,solo,category,openAmount}),getVisibleTriangles:()=>visibleTriangles};
 }catch(error){console.error(error);$('#loading').innerHTML='<b>상세 모델을 불러오지 못했습니다.</b><span>로컬 서버 연결을 확인하고 다시 시도해주세요.</span><button id="retry">다시 시도</button>';$('#retry').onclick=()=>location.reload();}}
function updateStatus(){visibleTriangles=data.reduce((n,d)=>n+(groups[d.id].visible?groups[d.id].userData.triangles:0),0);$('#status-line').textContent=`${visibleTriangles.toLocaleString()}개 삼각형 표시 · 원본 형상 보존 · 비공식 모델`;}
function updateMaterials(){for(const m of meshes){const b=m.material.userData.base,d=data.find(d=>d.id===m.userData.id)||catalog.find(d=>d.id===m.userData.id),shell=d.category==='외장';m.material.opacity=transparent&&shell?Math.min(.1,b.opacity):b.opacity;m.material.transparent=transparent&&shell?true:b.transparent;m.material.depthWrite=transparent&&shell?false:b.depthWrite;m.material.color.copy(b.color);m.material.metalness=b.metalness;m.material.roughness=b.roughness;m.material.emissive.copy(b.emissive);m.material.emissiveIntensity=b.intensity;if(m.userData.id===selected){m.material.emissive.set('#65c4cb');m.material.emissiveIntensity=d.category==='외장'?0:.018;}if(allSelected){m.material.color.set('#ef3530');m.material.emissive.set('#e52d24');m.material.emissiveIntensity=.32;m.material.metalness=.15;m.material.roughness=.45;m.material.opacity=1;m.material.transparent=false;m.material.depthWrite=true;}m.material.wireframe=$('#wireframe').checked;m.material.clippingPlanes=$('#section').checked?[cutPlane]:[];m.material.needsUpdate=true;}}
function renderList(){if(!ready)return;selectionButtons();const query=$('#search').value.trim().toLowerCase();$('#parts').innerHTML='';let n=0;for(const d of data){if(category!=='전체'&&d.category!==category)continue;if(!`${d.name} ${d.en} ${d.category}`.toLowerCase().includes(query))continue;n++;const row=document.createElement('div');row.className='part-row'+(allSelected||selected===d.id?' selected':'');const btn=document.createElement('button');btn.setAttribute('aria-pressed',allSelected||selected===d.id);btn.innerHTML=`<i class="dot" style="background:${d.color}"></i><span>${d.name}</span>`;btn.onclick=()=>select(d.id);const eye=document.createElement('button');eye.className='eye';eye.textContent=groups[d.id].visible?'◉':'○';eye.title=d.name+' 표시 전환';eye.setAttribute('aria-label',eye.title);eye.setAttribute('aria-pressed',groups[d.id].visible);eye.onclick=()=>{solo=null;groups[d.id].visible=!groups[d.id].visible;renderList();renderDetail();updateStatus();};row.append(btn,eye);$('#parts').appendChild(row);}$('#count').textContent=n+'개 그룹';if(!n)$('#parts').textContent='검색 결과가 없습니다.';}
function renderDetail(){const d=data.find(d=>d.id===selected);if(!d)return;const g=groups[selected];$('#detail').innerHTML=`<div class="component-icon" style="color:${d.color}">${d.category==='휠·제동'?'◉':d.category==='동력'?'⚙':'◈'}</div><span class="component-category">${d.category}</span><h2>${d.name}</h2><div class="english">${d.en}</div><div class="fidelity-badge">원본 3D 형상 사용</div><p class="description">${d.desc}</p>${vehicleLearning(d)}<div class="detail-box"><b>이 부품의 재현 범위</b><p>${d.limit}</p></div><div class="detail-box"><b>가져온 형상</b><p>${g.userData.triangles.toLocaleString()}개 삼각형 · ${g.userData.sourceNodes.size}개 원본 메시에서 분류</p></div>${['engine','engine-cover'].includes(d.id)?'<a class="bay-detail-link" href="/mechanics.html?system=bay">엔진룸 전체 · 내부 부품 탐색 →</a>':''}<div class="detail-actions"><button id="focus">부품 확대</button><button id="isolate">${solo===selected?'전체 보기':'이 부품만 보기'}</button><button id="hide-selected">${g.visible?'부품 숨기기':'부품 표시'}</button><button id="show-all">전체 표시</button></div><details class="detail-meta"><summary>원본 메시 이름</summary><div id="source-names"></div></details>`;$('#source-names').textContent=[...g.userData.sourceNodes].map(n=>n.split('_Geo')[0]).join(' · ');$('#focus').onclick=()=>focusPart();$('#isolate').onclick=()=>{solo=solo===selected?null:selected;for(const d of data)groups[d.id].visible=!solo||d.id===solo;renderList();renderDetail();updateStatus();if(solo)focusPart();else view('perspective');};$('#hide-selected').onclick=()=>{g.visible=!g.visible;solo=null;renderList();renderDetail();updateStatus();};$('#show-all').onclick=showAll;}
function select(id){if(!ready||!groups[id])return;allSelected=false;selected=id;updateMaterials();renderList();renderDetail();}
function selectionButtons(){$('#select-all').setAttribute('aria-pressed',allSelected);$('#undo-selection').disabled=!selectionSnapshot;$('#selection-status').textContent=allSelected?`${data.length}개 전체 선택 · 빨간색 강조`:'검색과 관계없이 현재 구성 전체 선택';}
$('#select-all').onclick=()=>{if(!ready)return;if(!selectionSnapshot)selectionSnapshot={selected,solo,visible:data.filter(d=>groups[d.id].visible).map(d=>d.id)};allSelected=true;solo=null;for(const d of data)groups[d.id].visible=true;updateMaterials();renderList();renderDetail();updateStatus();};
$('#undo-selection').onclick=()=>{if(!selectionSnapshot)return;const s=selectionSnapshot;selectionSnapshot=null;allSelected=false;selected=s.selected;solo=s.solo;for(const d of data)groups[d.id].visible=s.visible.includes(d.id);updateMaterials();renderList();renderDetail();updateStatus();};
function showAll(){solo=null;for(const d of data)groups[d.id].visible=true;renderList();renderDetail();updateStatus();}
function fitBox(box,direction=new THREE.Vector3(1,.6,1),padding=1.15,componentBoxes=null){
 const center=box.getCenter(new THREE.Vector3());direction.normalize();
 const right=new THREE.Vector3().crossVectors(new THREE.Vector3(0,1,0),direction).normalize();
 if(right.lengthSq()<.001)right.set(1,0,0);
 const up=new THREE.Vector3().crossVectors(direction,right).normalize();
 const tanV=Math.tan(THREE.MathUtils.degToRad(camera.fov)/2),tanH=tanV*camera.aspect;
 let distance=.65,verticalExtent=0;
 for(const sb of componentBoxes||[box])for(const x of [sb.min.x,sb.max.x])for(const y of [sb.min.y,sb.max.y])for(const z of [sb.min.z,sb.max.z]){
  const p=new THREE.Vector3(x,y,z).sub(center),depth=p.dot(direction),vx=Math.abs(p.dot(right)),vy=Math.abs(p.dot(up));
  distance=Math.max(distance,depth+vx*padding/(tanH*.94),depth+vy*padding/(tanV*.83));verticalExtent=Math.max(verticalExtent,vy);
 }
 // Reserve space for the viewer heading without making the model unnecessarily small.
 center.addScaledVector(up,verticalExtent*.12);controls.target.copy(center);camera.position.copy(center).addScaledVector(direction,distance);controls.update();
}
function focusPart(){if(!ready)return;groups[selected].visible=true;car.updateMatrixWorld(true);fitBox(new THREE.Box3().setFromObject(groups[selected]),camera.position.clone().sub(controls.target),1.12);renderList();updateStatus();}
function setExplosion(v){if(!ready)return;targetExplosion=v;$('#explode').value=Math.round(v*100);$('#explode-value').textContent=Math.round(v*100)+'%';$('#assembled').classList.toggle('active',v===0);$('#exploded').classList.toggle('active',v>0);$('#view-title').textContent=v?'원본 형상으로 보는 분해도':'상세 완성차 둘러보기';if(v>0){for(const id of ['hood-open','doors-open','trunk-open'])$('#'+id).checked=false;const b=new THREE.Box3(),boxes=[];for(const d of data){const g=groups[d.id];if(!g.visible)continue;const partBox=bounds[d.id].clone().translate(g.userData.pivot.clone().addScaledVector(g.userData.offset,v));b.union(partBox);boxes.push(partBox);}fitBox(b,new THREE.Vector3(1,.48,1),1.03,boxes);}}
function view(type){if(!ready)return;const direction={perspective:[1,.58,1.15],side:[0,.03,1],front:[1,.06,0],top:[0,1,.001]}[type];const b=new THREE.Box3(),boxes=[];for(const d of data){if(groups[d.id].visible){const partBox=bounds[d.id].clone().translate(groups[d.id].userData.pivot.clone().addScaledVector(groups[d.id].userData.offset,targetExplosion));b.union(partBox);boxes.push(partBox);}}if(b.isEmpty())return;fitBox(b,new THREE.Vector3(...direction),1.03,boxes);document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===type));}
function reset(){if(!ready)return;selectionSnapshot=null;allSelected=false;showAll();transparent=false;for(const id of ['transparent','label-toggle','wireframe','hood-open','doors-open','trunk-open','section'])$('#'+id).checked=false;$('#section-control').hidden=true;$('#section-position').value=0;cutPlane.constant=0;controls.autoRotate=false;$('#rotate').classList.remove('active');$('#rotate').setAttribute('aria-pressed','false');$('#search').value='';category='전체';document.querySelectorAll('[data-category]').forEach(b=>b.classList.toggle('active',b.dataset.category===category));setExplosion(0);select('body');view('perspective');}
$('#explode').oninput=e=>setExplosion(+e.target.value/100);$('#assembled').onclick=()=>{setExplosion(0);view('perspective');};$('#exploded').onclick=()=>setExplosion(1);$('#transparent').onchange=e=>{transparent=e.target.checked;updateMaterials();};$('#wireframe').onchange=updateMaterials;$('#search').oninput=renderList;$('#reset').onclick=reset;
document.querySelectorAll('[data-category]').forEach(b=>b.onclick=()=>{category=b.dataset.category;document.querySelectorAll('[data-category]').forEach(n=>n.classList.toggle('active',n===b));renderList();});document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>view(b.dataset.view));
$('#rotate').onclick=()=>{controls.autoRotate=!controls.autoRotate;$('#rotate').classList.toggle('active',controls.autoRotate);$('#rotate').setAttribute('aria-pressed',controls.autoRotate);};for(const id of ['hood-open','doors-open','trunk-open'])$('#'+id).onchange=()=>{if(targetExplosion>0)setExplosion(0);};
$('#section').onchange=e=>{$('#section-control').hidden=!e.target.checked;updateMaterials();};$('#section-position').oninput=e=>{cutPlane.constant=+e.target.value/100;};
$('#engine-view').onclick=()=>{reset();$('#hood-open').checked=true;select('engine');fitBox(new THREE.Box3(new THREE.Vector3(.9,.1,-.85),new THREE.Vector3(2.15,1.5,.85)),new THREE.Vector3(1,1.5,.6),1.15);};
$('#cabin-view').onclick=()=>{reset();$('#doors-open').checked=true;for(const id of ['roof','glass'])groups[id].visible=false;select('dashboard');fitBox(new THREE.Box3(new THREE.Vector3(-1.6,.15,-.95),new THREE.Vector3(1,1.6,.95)),new THREE.Vector3(-.3,1.2,1),1.1);updateStatus();renderList();};
$('#brakes-view').onclick=()=>{reset();for(const d of data)groups[d.id].visible=d.id==='brake-fr';solo='brake-fr';select('brake-fr');focusPart();updateStatus();renderList();};
$('#capture').onclick=()=>{if(!ready)return;renderer.render(scene,camera);const image=document.createElement('canvas');image.width=renderer.domElement.width;image.height=renderer.domElement.height;const ctx=image.getContext('2d');ctx.fillStyle='#f1f5f7';ctx.fillRect(0,0,image.width,image.height);ctx.drawImage(renderer.domElement,0,0);ctx.fillStyle='#405c68';ctx.font=`${Math.max(12,Math.round(image.width*.01))}px sans-serif`;ctx.fillText('2024 Hyundai Elantra N · Ddiaz Design · CC BY-NC 4.0 · modified in AUTO ATLAS',18,image.height-18);const link=document.createElement('a');link.download='auto-atlas-elantra-n.png';link.href=image.toDataURL('image/png');link.click();};
const dialog=$('#sources');$('#sources-button').onclick=$('#inside').onclick=()=>dialog.showModal();$('#close-sources').onclick=()=>dialog.close();dialog.onclick=e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}};
const raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2();let down,hoverTime=0;
function pick(e){if(!ready)return;const rect=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1);raycaster.setFromCamera(pointer,camera);return raycaster.intersectObjects(meshes).find(h=>groups[h.object.userData.id].visible&&!(transparent&&catalog.find(d=>d.id===h.object.userData.id).category==='외장')&&(!$('#section').checked||cutPlane.distanceToPoint(h.point)>=0));}
renderer.domElement.addEventListener('pointerdown',e=>{down=[e.clientX,e.clientY];$('#hover-name').hidden=true;});renderer.domElement.addEventListener('pointerup',e=>{if(!down||Math.hypot(e.clientX-down[0],e.clientY-down[1])>5||e.button!==0){down=null;return;}down=null;const hit=pick(e);if(hit)select(hit.object.userData.id);});renderer.domElement.addEventListener('dblclick',e=>{const hit=pick(e);if(hit){select(hit.object.userData.id);focusPart();}});renderer.domElement.addEventListener('pointermove',e=>{if(down||e.timeStamp-hoverTime<90)return;hoverTime=e.timeStamp;const hit=pick(e),label=$('#hover-name');label.hidden=!hit;renderer.domElement.style.cursor=hit?'pointer':'grab';if(hit){label.textContent=data.find(d=>d.id===hit.object.userData.id).name;const r=host.getBoundingClientRect();label.style.left=Math.min(host.clientWidth-160,e.clientX-r.left+12)+'px';label.style.top=e.clientY-r.top-28+'px';}});renderer.domElement.addEventListener('pointerleave',()=>{$('#hover-name').hidden=true;down=null;});
const labels={};function createLabels(){for(const d of data){const n=document.createElement('span');n.className='part-label';n.textContent=d.name;n.hidden=true;$('#labels').appendChild(n);labels[d.id]=n;}}
function resize(){const w=host.clientWidth,h=host.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();if(ready)view('perspective');}new ResizeObserver(resize).observe(host);resize();
let last=0;const screenPoint=new THREE.Vector3();function animate(time){requestAnimationFrame(animate);const dt=Math.min((time-last)/1000,.08),ease=1-Math.exp(-dt*7);last=time;explosion=THREE.MathUtils.lerp(explosion,targetExplosion,ease);for(const k of ['hood','doors','trunk'])openAmount[k]=THREE.MathUtils.lerp(openAmount[k],$('#'+k+'-open').checked?1:0,ease);
 for(const d of data){const g=groups[d.id];g.position.copy(g.userData.pivot).addScaledVector(g.userData.offset,explosion);g.rotation.set(0,0,0);if(d.id==='hood')g.rotation.z=openAmount.hood*1.07;if(d.id==='trunk')g.rotation.z=-openAmount.trunk*.95;if(d.id.startsWith('door-'))g.rotation.y=openAmount.doors*(d.id.endsWith('l')?-.9:.9);}
 controls.update();renderer.render(scene,camera);
 if(ready){const show=$('#label-toggle').checked,occupied=[];const sorted=[...data].sort((a,b)=>(b.id===selected)-(a.id===selected));for(const d of sorted){const label=labels[d.id],g=groups[d.id];label.hidden=true;if(!show||!g.visible)continue;screenPoint.copy(localCenters[d.id]);g.localToWorld(screenPoint);screenPoint.project(camera);if(Math.abs(screenPoint.x)>.96||Math.abs(screenPoint.y)>.94||screenPoint.z>1)continue;const x=(screenPoint.x*.5+.5)*host.clientWidth,y=(-screenPoint.y*.5+.5)*host.clientHeight;if(y<135||occupied.some(p=>Math.abs(p.x-x)<104&&Math.abs(p.y-y)<22))continue;occupied.push({x,y});label.hidden=false;label.classList.toggle('chosen',d.id===selected);label.style.left=x+'px';label.style.top=y+'px';}}
}requestAnimationFrame(animate);load();

installQuestions({context:()=>{const options=data.map(d=>({system:'car',kind:'part',id:d.id,name:d.name}));return {refs:options.filter(r=>r.id===selected),options};}});
