import {installQuestions} from './questions.js';
import {CURRICULUM} from './systems-curriculum.js';
import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {buildMechanical} from './mechanical-models.js';
import {buildEngineBay} from './engine-bay.js';
import {buildDrivetrain} from './drivetrain-model.js';
import {installSystemsUI,createSystemsLab,systemEducation} from './systems-learning.js';
import {systemFact} from './system-part-facts.js';
import {makeEngineMotion,cylinderState} from './engine-motion.js';
import {LESSONS,STROKES,learningFor} from './engine-learning-data.js';
import {installLearningUI,educationalDetail} from './engine-learning-ui.js';
installLearningUI();installSystemsUI();
const $=s=>document.querySelector(s),host=$('#canvas');
const renderer=new T.WebGLRenderer({antialias:true,alpha:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.8));renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.2;host.append(renderer.domElement);
const scene=new T.Scene(),camera=new T.PerspectiveCamera(36,1,.03,150);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.minDistance=.3;controls.maxDistance=40;
const generator=new T.PMREMGenerator(renderer),room=new RoomEnvironment();scene.environment=generator.fromScene(room,.03).texture;room.dispose();generator.dispose();scene.add(new T.HemisphereLight(0xf0f7ff,0x768b9a,2));for(const [pos,power,color]of [[[3,6,5],3,0xfff2df],[[-4,3,-3],2,0xd9f1ff]]){const light=new T.DirectionalLight(color,power);light.position.set(...pos);scene.add(light);}
const grid=new T.GridHelper(16,32,0xbecfd6,0xdae4e8);grid.position.y=-1.05;grid.material.transparent=true;grid.material.opacity=.32;scene.add(grid);
let model,parts=[],selected=null,system='',amount=.35,target=.35,solo=null,showLabels=false;
let learning=false,playing=false,cycleAngle=90,cycleSpeed=1,singleCylinder=true,lessonIndex=0,engineMotion=null,structureSnapshot=null,lastStroke=-1;
let systemLab=null,allSelected=false,selectionSnapshot=null;
const snapshots={};
const initialPart=new URLSearchParams(location.search).get('part');
const descriptions={drivetrain:{title:'동력 전달 · 조향',intro:'클러치 · 기어 · 차동 · 구동축 · 랙',scope:'일반 단판 클러치·한 쌍의 외접 기어·오픈 차동기어·평면 랙 조향을 기능별로 펼친 참고 모델입니다. 실제 아반떼의 6MT/8DCT 내부·e-LSD·EPS 제어·타이어 미끄럼을 재현하지 않았습니다.'},bay:{title:'엔진룸 전체 구성',intro:'가로배치 2.0 터보 · 계통별 구조 참고',scope:'엔진룸의 주요 장치·대표 배관을 재구성했습니다. 현대 공식 자료의 2.0 터보 구성과 부품 제조사의 기능 설명을 참고했으며, 실제 CN7 장착 좌표·배관 경로·BOM은 검증하지 않았습니다. 모든 볼트·클립·씰·배선, 실내/연료탱크 계통과 변속기 내부는 미포함입니다.'},engine:{title:'직렬 4기통 엔진',intro:'DOHC · 16밸브 구조 참고 모델',scope:'블록·크랭크·피스톤·밸브·타이밍 구성에 집중했습니다. 작동 모드는 로드 길이와 크랭크/캠 2:1 관계를 유지하는 학습용 기구 운동입니다. 실제 치수·점화 진각·밸브 겹침·가변 타이밍·태핏 접촉·압력/토크 계산은 생략했습니다. 실제 엔진 RPM이나 제조사 동작 해석이 아닙니다.'},suspension:{title:'전륜 맥퍼슨 구조',intro:'스트럿 · 허브 · 조향 링크 · 제동계',scope:'한쪽 전륜의 연결 관계를 재구성했습니다. 댐퍼 내부는 일반적인 트윈 튜브 참고 구조이며 아반떼 N ECS 설계가 아닙니다. 차체 체결 좌표·전자제어 밸브·후륜 서스펜션은 재현하지 않았습니다.'}};
function load(name,lessonRequest=null){
 clearBatchSelection();
 const initialLesson=new URLSearchParams(location.search).get('lesson');
 if(learning)stopLearning();systemLab?.stop();systemLab=null;engineMotion=null;
 if(model){snapshots[system]={selected:selected.userData.id,target,ghost:$('#ghost').checked,wire:$('#wire').checked,query:$('#search').value,visible:parts.filter(p=>p.visible).map(p=>p.userData.id),camera:camera.position.toArray(),look:controls.target.toArray(),solo:solo?.userData.id};scene.remove(model.root);model.root.traverse(o=>{if(o.geometry){o.geometry.dispose();o.material.dispose();}});}
 system=name;model=name==='bay'?buildEngineBay():name==='drivetrain'?buildDrivetrain():buildMechanical(name);parts=model.parts;scene.add(model.root);if(name==='engine')engineMotion=makeEngineMotion(model);$('#engine-guide').hidden=name!=='engine';
 const saved=snapshots[name];selected=parts.find(p=>p.userData.id===(saved?.selected||(name==='bay'?'engine-assembly':name==='engine'?'piston-0':name==='drivetrain'?'friction-disc':'coil')));solo=parts.find(p=>p.userData.id===saved?.solo)||null;amount=target=saved?.target??(name==='bay'?.12:.35);$('#explode').value=Math.round(target*100);$('#amount').textContent=Math.round(target*100)+'%';$('#search').value=saved?.query||'';$('#ghost').checked=saved?.ghost??(name!=='bay');$('#wire').checked=saved?.wire??false;
 if(saved)for(const p of parts)p.visible=saved.visible.includes(p.userData.id);
 $('#title').textContent=descriptions[name].title;$('#intro').textContent=descriptions[name].intro;$('#scope').textContent=descriptions[name].scope;$('#total').textContent=parts.length+'개';$('#scene-title').textContent=name==='bay'?'엔진룸에서, 개별 부품 안으로':name==='engine'?'피스톤부터 밸브까지':name==='drivetrain'?'엔진 다음, 바퀴에 닿는 회전':'스프링 안쪽까지 들여다보기';
 $('#breadcrumb').innerHTML=name==='bay'?'<a href="/">완성차</a><span>›</span><b>엔진룸 계통 · 개별 부품</b>':`<a href="/">완성차</a><span>›</span><button id="back-bay">엔진룸 전체</button><span>›</span><b>${name==='engine'?'엔진 내부':name==='drivetrain'?'동력 전달·조향':'서스펜션 내부'}</b>`;
 if($('#back-bay'))$('#back-bay').onclick=()=>load('bay');
 $('#bay-note').hidden=name!=='bay';$('#top').hidden=name!=='bay';
 document.querySelectorAll('[data-system]').forEach(b=>b.classList.toggle('active',b.dataset.system===name));$('#labels-host').innerHTML='';for(const p of parts){const el=document.createElement('span');el.className='mech-label';el.textContent=p.userData.name;el.hidden=true;$('#labels-host').append(el);p.userData.label=el;}position();select(selected);fit();if(saved){camera.position.fromArray(saved.camera);controls.target.fromArray(saved.look);controls.update();}updateButtons();history.replaceState(null,'','?system='+name);window.__mechanics={scene,camera,renderer,parts,system,getState:()=>({allSelected,selected:selected.userData.id,amount,target,solo:solo?.userData.id,visible:parts.filter(p=>p.visible).length,learning,playing,cycleAngle,singleCylinder,lessonIndex}),getCycle:()=>[0,1,2,3].map(i=>cylinderState(cycleAngle,i)),getSystemLearning:()=>systemLab?.getState()||null};systemLab=createSystemsLab({system:name,model,save:saveSystemState,restore:restoreSystemState,prepare:prepareSystemLesson,select:p=>select(p,true),refresh:()=>{apply();list();detail();},fit,navigate:load});if(name==='engine'){const requestedIndex=Number(lessonRequest??initialLesson??lessonIndex);startLearning(Number.isInteger(requestedIndex)&&LESSONS[requestedIndex]?requestedIndex:lessonIndex);}if(systemLab&&(lessonRequest!==null||initialLesson!==null))systemLab.start(lessonRequest??initialLesson);
}
function position(value=amount){for(const p of parts)p.position.copy(p.userData.base).addScaledVector(p.userData.offset,value);model.root.updateMatrixWorld(true);}
function apply(){for(const p of parts)p.traverse(m=>{
 if(!m.isMesh)return;
 const material=m.material;
 material.userData.selectionBase??={color:material.color.clone(),metalness:material.metalness,roughness:material.roughness};
 const base=material.userData.selectionBase,chosen=allSelected||p===selected;
 const transparent=!chosen&&$('#ghost').checked&&p.userData.shell;
 material.transparent=transparent;material.opacity=transparent?(learning?.075:.14):1;material.depthWrite=!transparent;
 material.color.copy(base.color);material.metalness=base.metalness;material.roughness=base.roughness;
 material.emissive.set(chosen?0xe52d24:0);material.emissiveIntensity=chosen?.32:0;
 if(chosen){material.color.set('#ef3530');material.metalness=.15;material.roughness=.45;}
 material.wireframe=$('#wire').checked;
 });}

function list(){selectionButtons();const open=new Set([...$('#list').querySelectorAll('details[open]')].map(d=>d.dataset.category));const query=$('#search').value.toLowerCase().trim(),categories=[...new Set(parts.map(p=>p.userData.category))];$('#list').innerHTML='';for(const category of categories){const subset=parts.filter(p=>p.userData.category===category&&`${p.userData.name} ${p.userData.en}`.toLowerCase().includes(query));if(!subset.length)continue;const group=document.createElement('details');group.dataset.category=category;group.open=query||open.has(category)||selected.userData.category===category;const summary=document.createElement('summary');summary.innerHTML=category+`<span>${subset.length}</span>`;group.append(summary);for(const p of subset){const row=document.createElement('div');row.className='row'+(allSelected||p===selected?' selected':'')+(p.visible?'':' hidden');row.style.setProperty('--part-color',p.userData.color);const selectButton=document.createElement('button');selectButton.innerHTML='<i></i>'+p.userData.name;selectButton.dataset.part=p.userData.id;selectButton.setAttribute('aria-pressed',allSelected||p===selected);selectButton.onclick=()=>select(p);const eye=document.createElement('button');eye.textContent=p.visible?'◉':'○';eye.setAttribute('aria-label',p.userData.name+' 표시 전환');eye.onclick=()=>{p.visible=!p.visible;solo=null;list();detail();};row.append(selectButton,eye);group.append(row);}$('#list').append(group);}if(!$('#list').children.length)$('#list').textContent='검색 결과가 없습니다.';}
function detail(){const d=selected.userData;$('#detail').innerHTML=`<div class="part-symbol" style="--part-color:${d.color}">⚙</div><span class="eyebrow">${d.category}</span><h2>${d.name}</h2><div class="english">${d.en}</div><div class="badge selection-key">● 빨간색: 선택한 부품</div><p class="desc">${d.desc}</p>${system==='engine'?educationalDetail(selected,parts):systemEducation(system,selected,parts)}<div class="connections"><b>연결 관계</b><br>${d.connect}</div>${d.drill?`<button class="drill" id="drill">${d.drill==='engine'?'엔진 내부 80개 그룹 탐색':d.drill==='drivetrain'?'동력 전달·조향 내부 탐색':'서스펜션 내부 29개 그룹 탐색'} →</button>`:''}<div class="actions"><button id="focus">부품 확대</button><button id="isolate">${solo===selected?'전체 보기':'이 부품만'}</button><button id="hide">${selected.visible?'부품 숨기기':'부품 표시'}</button><button id="family">같은 계통만</button></div>`;document.querySelectorAll('[data-related]').forEach(b=>b.onclick=()=>{const p=parts.find(p=>p.userData.id===b.dataset.related);if(p){p.visible=true;select(p);}});if($('#related-view'))$('#related-view').onclick=()=>{const ids=new Set([d.id,...(system==='engine'?learningFor(d.id):systemFact(system,selected,parts)).related]);if(learning)stopLearning();systemLab?.stop();selected=parts.find(p=>p.userData.id===d.id);for(const p of parts)p.visible=ids.has(p.userData.id);solo=null;target=amount=.4;$('#explode').value=40;$('#amount').textContent='40%';position();updateButtons();list();detail();fit();};document.querySelectorAll('[data-start-lesson]').forEach(b=>b.onclick=()=>systemLab?.start(+b.dataset.startLesson));if($('#drill'))$('#drill').onclick=()=>load(d.drill);$('#focus').onclick=()=>{selected.visible=true;list();detail();fit(selected);};$('#isolate').onclick=()=>{solo=solo===selected?null:selected;for(const p of parts)p.visible=!solo||p===solo;list();detail();fit(solo);};$('#hide').onclick=()=>{selected.visible=!selected.visible;solo=null;list();detail();};$('#family').onclick=()=>{solo=null;for(const p of parts)p.visible=p.userData.category===selected.userData.category;list();detail();fit();};}
function select(p,preserveBatch=false){if(!preserveBatch)allSelected=false;selected=p;p.visible=true;apply();list();detail();}
function selectionButtons(){
 $('#select-all').setAttribute('aria-pressed',allSelected);$('#undo-selection').disabled=!selectionSnapshot;
 $('#selection-status').textContent=allSelected?`${parts.length}개 전체 선택 · 빨간색 강조`:'검색과 관계없이 현재 구성 전체 선택';
}
function undoSelection(){
 if(!selectionSnapshot)return;const s=selectionSnapshot;selectionSnapshot=null;allSelected=false;
 selected=parts.find(p=>p.userData.id===s.selected);solo=parts.find(p=>p.userData.id===s.solo)||null;
 for(const p of parts)p.visible=s.visible.includes(p.userData.id);
 camera.position.fromArray(s.camera);controls.target.fromArray(s.look);controls.update();apply();list();detail();
}
function clearBatchSelection(){undoSelection();allSelected=false;selectionSnapshot=null;selectionButtons();}
$('#select-all').onclick=()=>{if(!selectionSnapshot)selectionSnapshot=saveSystemState();allSelected=true;solo=null;for(const p of parts)p.visible=true;apply();list();detail();fit();};
$('#undo-selection').onclick=undoSelection;
function fit(part=null,dir=null){const b=new T.Box3(),fitBoxes=[];position(target);for(const p of part?[part]:parts.filter(p=>p.visible)){const pb=new T.Box3().setFromObject(p);b.union(pb);fitBoxes.push(pb);}position();if(b.isEmpty())return;const direction=dir||(system==='bay'?new T.Vector3(1.1,1.9,2):new T.Vector3(system==='engine'?1.3:1,.7,system==='engine'?1.65:2));direction.normalize();const center=b.getCenter(new T.Vector3()),size=b.getSize(new T.Vector3());const right=new T.Vector3().crossVectors(new T.Vector3(0,1,0),direction).normalize(),up=new T.Vector3().crossVectors(direction,right);let distance=1,extent=0;const tan=Math.tan(T.MathUtils.degToRad(camera.fov)/2);for(const bb of system==='bay'?fitBoxes:[b])for(const x of [bb.min.x,bb.max.x])for(const y of [bb.min.y,bb.max.y])for(const z of [bb.min.z,bb.max.z]){const q=new T.Vector3(x,y,z).sub(center);distance=Math.max(distance,q.dot(direction)+Math.abs(q.dot(right))/(tan*camera.aspect*.88),q.dot(direction)+Math.abs(q.dot(up))/(tan*.72));extent=Math.max(extent,Math.abs(q.dot(up)));}center.addScaledVector(up,extent*.15);controls.target.copy(center);camera.position.copy(center).addScaledVector(direction,distance);controls.update();}
function updateButtons(){$('#assemble').classList.toggle('active',target===0);$('#explode-all').classList.toggle('active',target>0);}
function explode(value){if(learning)stopLearning();systemLab?.stop();target=value;$('#explode').value=Math.round(value*100);$('#amount').textContent=Math.round(value*100)+'%';updateButtons();fit();}
$('#explode').oninput=e=>explode(+e.target.value/100);$('#explode-all').onclick=()=>explode(1);$('#assemble').onclick=()=>explode(0);$('#search').oninput=list;$('#ghost').onchange=apply;$('#wire').onchange=apply;$('#restore').onclick=()=>{for(const p of parts)p.visible=true;solo=null;list();detail();fit();};$('#internals').onclick=()=>{for(const p of parts)p.visible=!p.userData.shell;solo=null;list();detail();fit();};$('#home').onclick=()=>fit();$('#front').onclick=()=>fit(null,new T.Vector3(0,.05,1));$('#side').onclick=()=>fit(null,new T.Vector3(1,.05,0));$('#top').onclick=()=>fit(null,new T.Vector3(0,1,.001));$('#labels').onclick=()=>{showLabels=!showLabels;$('#labels').setAttribute('aria-pressed',showLabels);$('#labels').textContent=showLabels?'이름 숨김':'이름 표시';};document.querySelectorAll('[data-system]').forEach(b=>b.onclick=()=>load(b.dataset.system));
$('#capture').onclick=()=>{renderer.render(scene,camera);const c=document.createElement('canvas');c.width=renderer.domElement.width;c.height=renderer.domElement.height;const ctx=c.getContext('2d');ctx.fillStyle='#eff4f6';ctx.fillRect(0,0,c.width,c.height);ctx.drawImage(renderer.domElement,0,0);ctx.fillStyle='#466575';ctx.font='14px sans-serif';ctx.fillText('AUTO ATLAS · '+descriptions[system].title+' · 구조 참고 재구성 / 제조사 CAD 아님',15,c.height-16);const a=document.createElement('a');a.download='auto-atlas-'+system+'.png';a.href=c.toDataURL();a.click();};
const ray=new T.Raycaster(),mouse=new T.Vector2();let down;
function pick(e){const r=host.getBoundingClientRect();mouse.set((e.clientX-r.left)/r.width*2-1,1-(e.clientY-r.top)/r.height*2);ray.setFromCamera(mouse,camera);const hits=ray.intersectObjects(parts.filter(p=>p.visible),true);return hits.find(h=>!($('#ghost').checked&&h.object.userData.part.userData.shell))?.object.userData.part||hits[0]?.object.userData.part;}
renderer.domElement.onpointerdown=e=>{down=[e.clientX,e.clientY];};renderer.domElement.onpointerup=e=>{if(down&&e.button===0&&Math.hypot(e.clientX-down[0],e.clientY-down[1])<5){const p=pick(e);if(p)select(p);}down=null;};renderer.domElement.ondblclick=e=>{const p=pick(e);if(p){select(p);fit(p);}};renderer.domElement.onpointermove=e=>{const p=pick(e),r=host.getBoundingClientRect();$('#tag').hidden=!p||!!down;if(p){$('#tag').textContent=p.userData.name;$('#tag').style.left=Math.min(e.clientX-r.left+10,host.clientWidth-170)+'px';$('#tag').style.top=e.clientY-r.top-30+'px';}renderer.domElement.style.cursor=p?'pointer':'grab';};renderer.domElement.onpointerleave=()=>{$('#tag').hidden=true;down=null;};
function resize(){const w=host.clientWidth,h=host.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();if(model)fit();}new ResizeObserver(resize).observe(host);resize();
let last=0;function frame(time){requestAnimationFrame(frame);const dt=Math.min((time-last)/1000,.05);last=time;if(!model)return;amount=T.MathUtils.lerp(amount,target,1-Math.exp(-dt*8));position();if(learning){if(playing&&!document.hidden)cycleAngle=(cycleAngle+dt*90*cycleSpeed)%720;engineMotion.pose(cycleAngle,singleCylinder);updateCycleUI();}systemLab?.frame(dt);controls.update();renderer.render(scene,camera);const occupied=[];for(const p of [...parts].sort((a,b)=>(b===selected)-(a===selected))){const el=p.userData.label;el.hidden=true;if(!showLabels||!p.visible)continue;const center=new T.Box3().setFromObject(p).getCenter(new T.Vector3()).project(camera);const x=(center.x*.5+.5)*host.clientWidth,y=(.5-center.y*.5)*host.clientHeight;if(center.z>1||center.z< -1||x<40||x>host.clientWidth-50||y<115||y>host.clientHeight-35||occupied.some(q=>Math.abs(q.x-x)<120&&Math.abs(q.y-y)<25))continue;occupied.push({x,y});el.hidden=false;el.classList.toggle('selected',allSelected||p===selected);el.style.left=x+'px';el.style.top=y+'px';}}

function learningVisibility(){
 clearBatchSelection();
 for(const p of parts){const id=p.userData.id;let cylinder=null;const m=id.match(/^(?:piston|pin|rod|rod-cap|ring|plug)-(\d)/);if(m)cylinder=+m[1];const v=id.match(/^(?:valve|spring)-(-?1)-(\d)-/);if(v)cylinder=+v[2];p.visible=!['cover','pan','pickup'].includes(id)&&(!singleCylinder||cylinder===null||cylinder===0);}
 $('#cylinder-view').textContent=singleCylinder?'4기통 함께':'1번 집중';list();
}
function setLesson(index){lessonIndex=index;const lesson=LESSONS[index];singleCylinder=lesson.single;lastStroke=-1;$('#lesson-heading').textContent=lesson.heading;$('#lesson-body').textContent=lesson.body;$('#quiz-question').textContent=lesson.question;$('#quiz-feedback').textContent='';$('#lesson-quiz').open=false;$('#quiz-options').innerHTML=lesson.answers.map((a,i)=>`<button data-answer="${i}">${a}</button>`).join('');document.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{const correct=+b.dataset.answer===lesson.correct;$('#quiz-feedback').textContent=(correct?'맞습니다. ':'다시 살펴보세요. ')+lesson.feedback;document.querySelectorAll('[data-answer]').forEach(n=>n.classList.toggle('correct',+n.dataset.answer===lesson.correct));});document.querySelectorAll('[data-lesson]').forEach(b=>b.classList.toggle('active',+b.dataset.lesson===index));$('#energy-path').hidden=index!==4;learningVisibility();select(parts.find(p=>p.userData.id===lesson.part));fit();updateCycleUI();}
function startLearning(index=lessonIndex){
 if(system!=='engine')return;
 if(!learning){structureSnapshot={target,selected:selected.userData.id,visible:parts.filter(p=>p.visible).map(p=>p.userData.id),ghost:$('#ghost').checked,wire:$('#wire').checked,solo:solo?.userData.id,camera:camera.position.toArray(),look:controls.target.toArray()};learning=true;playing=false;cycleAngle=90;target=amount=0;solo=null;$('#ghost').checked=true;$('#wire').checked=false;$('#explode').value=0;$('#amount').textContent='0%';}
 $('#viewport').classList.add('learning-active');$('.control-panel').hidden=true;$('#cycle-panel').hidden=false;$('#lesson-card').hidden=false;$('#stroke-status').hidden=false;$('#learning-mode').classList.add('active');$('#structure-mode').classList.remove('active');$('#scene-title').textContent='움직임을 멈춰 가며 원리 살펴보기';setLesson(index);position();engineMotion.pose(cycleAngle,singleCylinder);apply();updateButtons();}
function stopLearning(){
 if(!learning)return;clearBatchSelection();learning=false;playing=false;engineMotion.reset();$('#viewport').classList.remove('learning-active');$('.control-panel').hidden=false;$('#cycle-panel').hidden=true;$('#lesson-card').hidden=true;$('#stroke-status').hidden=true;$('#learning-mode').classList.remove('active');$('#structure-mode').classList.add('active');$('#scene-title').textContent='피스톤부터 밸브까지';
 if(structureSnapshot){const b=structureSnapshot;target=amount=b.target;selected=parts.find(p=>p.userData.id===b.selected);solo=parts.find(p=>p.userData.id===b.solo)||null;for(const p of parts)p.visible=b.visible.includes(p.userData.id);$('#ghost').checked=b.ghost;$('#wire').checked=b.wire;$('#explode').value=Math.round(target*100);$('#amount').textContent=Math.round(target*100)+'%';position();apply();list();detail();updateButtons();camera.position.fromArray(b.camera);controls.target.fromArray(b.look);controls.update();}}
function updateCycleUI(){
 const state=cylinderState(cycleAngle),stroke=STROKES[state.stroke];$('#play-cycle').textContent=playing?'Ⅱ 일시정지':'▶ 반복 재생';$('#play-cycle').setAttribute('aria-pressed',playing);if(document.activeElement!==$('#cycle-angle'))$('#cycle-angle').value=Math.round(cycleAngle);$('#angle-value').textContent=Math.round(cycleAngle)+'° / 720°';$('#cam-angle').textContent='캠축 '+Math.round(cycleAngle/2)+'°';$('#cycle-piston').textContent='1번 피스톤 '+stroke.direction;$('#cycle-intake').textContent='흡기 '+(state.intake>.0001?'열림':'닫힘');$('#cycle-exhaust').textContent='배기 '+(state.exhaust>.0001?'열림':'닫힘');
 if(lastStroke!==state.stroke){lastStroke=state.stroke;$('#stroke-heading').textContent='1번 실린더 · '+stroke.name+' — '+stroke.short;$('#stroke-description').textContent=stroke.text;$('#stroke-status').style.setProperty('--stroke',stroke.color);document.querySelectorAll('[data-stroke]').forEach(b=>b.classList.toggle('active',+b.dataset.stroke===state.stroke));}
 for(let i=0;i<4;i++){const s=STROKES[cylinderState(cycleAngle,i).stroke],el=$('#cylinder-state-'+i);el.textContent=(i+1)+'번 · '+s.name;el.style.setProperty('--stroke',s.color);} }
$('#learning-mode').onclick=()=>startLearning();$('#structure-mode').onclick=stopLearning;document.querySelectorAll('[data-lesson]').forEach(b=>b.onclick=()=>startLearning(+b.dataset.lesson));$('#play-cycle').onclick=()=>{playing=!playing;updateCycleUI();};$('#cycle-speed').onchange=e=>cycleSpeed=+e.target.value;$('#cycle-angle').oninput=e=>{playing=false;cycleAngle=+e.target.value;engineMotion.pose(cycleAngle,singleCylinder);updateCycleUI();};document.querySelectorAll('[data-stroke]').forEach(b=>b.onclick=()=>{playing=false;cycleAngle=+b.dataset.stroke*180+90;engineMotion.pose(cycleAngle,singleCylinder);updateCycleUI();});$('#next-stroke').onclick=()=>{playing=false;cycleAngle=(Math.floor((cycleAngle%720)/180)*180+270)%720;engineMotion.pose(cycleAngle,singleCylinder);updateCycleUI();};$('#cylinder-view').onclick=()=>{singleCylinder=!singleCylinder;learningVisibility();fit();};document.querySelectorAll('[data-power]').forEach(b=>b.onclick=()=>select(parts.find(p=>p.userData.id===b.dataset.power)));document.querySelector('#drive-learning-link').onclick=()=>load('drivetrain','power-path');
function saveSystemState(){return {selected:selected.userData.id,target,ghost:$('#ghost').checked,wire:$('#wire').checked,visible:parts.filter(p=>p.visible).map(p=>p.userData.id),solo:solo?.userData.id,camera:camera.position.toArray(),look:controls.target.toArray()};}
function restoreSystemState(s){clearBatchSelection();target=amount=s.target;selected=parts.find(p=>p.userData.id===s.selected);solo=parts.find(p=>p.userData.id===s.solo)||null;for(const p of parts)p.visible=s.visible.includes(p.userData.id);$('#ghost').checked=s.ghost;$('#wire').checked=s.wire;$('#explode').value=Math.round(target*100);$('#amount').textContent=Math.round(target*100)+'%';position();apply();list();detail();updateButtons();camera.position.fromArray(s.camera);controls.target.fromArray(s.look);controls.update();}
function prepareSystemLesson(ids){clearBatchSelection();target=amount=0;solo=null;$('#ghost').checked=true;$('#wire').checked=false;for(const p of parts)p.visible=ids.includes(p.userData.id);$('#explode').value=0;$('#amount').textContent='0%';position();updateButtons();}
const requested=new URLSearchParams(location.search).get('system');load(['bay','engine','suspension','drivetrain'].includes(requested)?requested:'bay');requestAnimationFrame(frame);

if(initialPart){const p=parts.find(p=>p.userData.id===initialPart);if(p){select(p);fit(p);}}
installQuestions({context:()=>{
 const partRefs=parts.map(p=>({system,kind:'part',id:p.userData.id,name:p.userData.name}));
 const lessons=system==='engine'?LESSONS:(CURRICULUM[system]||[]);
 const lessonRefs=lessons.map((l,i)=>({system,kind:'lesson',id:system==='engine'?String(i):l.id,name:l.title}));
 const lab=systemLab?.getState(),lesson=learning?lessonRefs[lessonIndex]:lab?.active?lessonRefs[lab.index]:null;
 return {refs:[...(selected?[partRefs.find(p=>p.id===selected.userData.id)]:[]),...(lesson?[lesson]:[])],options:[...lessonRefs,...partRefs]};
}});
