import assert from 'node:assert/strict';
import {inspectAssembly} from '../src/assembly-state.js';
export async function checkAssembly(page){
 await page.goto('http://127.0.0.1:5173/assembly.html');await page.waitForFunction(()=>window.__assembly,{},{timeout:20000});
 const catalog=await page.evaluate(()=>window.__assembly.catalog);assert.equal(catalog.length,80);assert.equal(await page.locator('[data-part]').count(),80);
 const perfect=Object.fromEntries(catalog.map(c=>[c.id,{slot:c.id,position:[0,0,0],rotation:[0,0,0]}]));assert.equal(inspectAssembly(catalog,{}).missing,80);assert(inspectAssembly(catalog,perfect).passed);
 const bad=structuredClone(perfect);delete bad['plug-0'];bad['piston-0'].slot='piston-1';bad['cam--1'].rotation=[90,0,0];const inspected=inspectAssembly(catalog,bad);assert.equal(inspected.missing,1);assert.equal(inspected.incorrect,3);assert(inspected.results.find(r=>r.id==='piston-1').issues.includes('occupied'));
 await page.screenshot({path:'artifacts/assembly-empty.png'});
 const target=await page.evaluate(()=>window.__assembly.slotScreen('block'));await page.locator('[data-part="block"]').hover();await page.mouse.down();await page.mouse.move(target.x,target.y,{steps:15});await page.mouse.up();await page.waitForTimeout(250);assert.equal(await page.evaluate(()=>window.__assembly.getState().placements.block?.slot),'block');
 const start=await page.evaluate(()=>window.__assembly.slotScreen('block'));const canvas=await page.locator('#canvas').boundingBox();await page.mouse.move(start.x,start.y);await page.mouse.down();await page.mouse.move(canvas.x+40,canvas.y+canvas.height-70,{steps:15});await page.mouse.up();assert.equal(await page.evaluate(()=>window.__assembly.getState().placements.block.slot),null);assert((await page.evaluate(()=>window.__assembly.inspect().results.find(r=>r.id==='block').issues)).includes('unseated'));await page.locator('#undo').click();
 await page.locator('[data-rotate="0"]').click();await page.locator('#check').click();assert((await page.locator('#report').textContent()).includes('기준 방향과 다름'));await page.locator('#attempt-note').fill('블록 방향을 90도 돌려 잘못 조립했다. 방향 복습하기.');await page.locator('#history-close').click();
 await page.locator('#undo').click();assert.equal(await page.evaluate(()=>window.__assembly.getState().placements.block.rotation[0]),0);
 await page.locator('#search').fill('점화 플러그');assert.equal(await page.locator('[data-part]').count(),4);await page.locator('[data-part="plug-0"]').click();await page.locator('#target-slot').selectOption('plug-1');await page.locator('#place-slot').click();assert.equal(await page.evaluate(()=>window.__assembly.getState().placements['plug-0'].slot),'plug-1');
 await page.locator('#check').click();assert((await page.locator('#report').textContent()).includes('다른 부품 자리에 배치'));assert.equal(await page.locator('.history-item').count(),2);await page.screenshot({path:'artifacts/assembly-errors.png'});await page.locator('#history-close').click();
 await page.reload();await page.waitForFunction(()=>window.__assembly);assert.equal(await page.evaluate(()=>window.__assembly.getState().attempts.length),2);assert.equal(await page.evaluate(()=>window.__assembly.getState().placements['plug-0'].slot),'plug-1');await page.locator('#history-open').click();await page.locator('.history-item').last().click();assert((await page.locator('#attempt-note').inputValue()).includes('블록 방향'));await page.locator('#resume-attempt').click();await page.locator('#resume-yes').click();assert(!await page.evaluate(()=>window.__assembly.getState().placements['plug-0']));assert.equal(await page.evaluate(()=>window.__assembly.getState().placements.block.rotation[0]),90);
 await page.locator('#restart').click();await page.locator('#restart-yes').click();assert.equal(await page.evaluate(()=>Object.keys(window.__assembly.getState().placements).length),0);assert.equal(await page.evaluate(()=>window.__assembly.getState().attempts.length),2);
 // Assemble all 80 through the keyboard-accessible placement UI.
 await page.locator('#search').fill('');for(const c of catalog){await page.locator(`[data-part="${c.id}"]`).click();await page.locator('#target-slot').selectOption(c.id);await page.locator('#place-slot').click();}
 assert(await page.evaluate(()=>window.__assembly.inspect().passed));await page.locator('#spread').fill('0');assert(await page.evaluate(()=>window.__assembly.parts.every(p=>p.position.distanceTo(p.userData.base)<1e-8)));await page.locator('#hints').uncheck();await page.locator('#shell').uncheck();await page.locator('#view-home').click();await page.screenshot({path:'artifacts/assembly-complete.png'});
 await page.locator('#check').click();assert((await page.locator('#report h2').textContent()).includes('80개'));assert.equal(await page.locator('.history-item').count(),3);await page.locator('#attempt-note').fill('완성! 다음에는 힌트 없이 도전하기.');const download=page.waitForEvent('download');await page.locator('#export-history').click();await(await download).saveAs('/tmp/engine-assembly-test.json');await page.screenshot({path:'artifacts/assembly-passed.png'});
 await page.locator('#history-close').click();await page.setViewportSize({width:390,height:844});await page.screenshot({path:'artifacts/assembly-mobile.png',fullPage:true});assert(!await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth));await page.locator('#history-open').click();assert(!await page.locator('#history').evaluate(e=>e.scrollWidth>e.clientWidth));
}
