import assert from 'node:assert/strict';
export async function checkQuestions(page){
 await page.goto('http://127.0.0.1:5173/mechanics.html?system=engine&lesson=0&part=plug-0');await page.waitForFunction(()=>window.__mechanics);assert.equal(await page.evaluate(()=>window.__mechanics.getState().selected),'plug-0');
 await page.evaluate(()=>localStorage.removeItem('auto-atlas.questions.v1'));await page.locator('#qa-open').click();await page.locator('#qa-new').click();assert.equal(await page.locator('#qa-refs button').count(),2);
 await page.locator('#qa-title').fill('점화플러그는 언제 불꽃을 만드나요?');await page.locator('#qa-body').fill('압축과 팽창 사이에서 어떻게 점화되나요? <img src=x onerror=alert(1)>');await page.locator('#qa-tags').fill('점화 시점, 연소, 연소');await page.locator('#qa-compose button[type=submit]').click();
 assert.equal(await page.locator('#qa-thread img').count(),0);assert.equal(await page.locator('.qa-item').count(),1);assert.equal(await page.locator('#qa-thread a').count(),2);
 await page.locator('#qa-answer-body').fill('압축 말기에 점화해 연소를 시작합니다. 이 학습 모델은 상사점 점화를 단순화해 보여줍니다.');await page.locator('#qa-answer-form button').click();assert.equal(await page.locator('.qa-answer').count(),1);
 await page.locator('#qa-search').fill('상사점');assert.equal(await page.locator('.qa-item').count(),1);await page.locator('#qa-status').selectOption('waiting');assert.equal(await page.locator('.qa-item').count(),0);await page.locator('#qa-status').selectOption('answered');assert.equal(await page.locator('.qa-item').count(),1);
 await page.locator('#qa-resolve').click();await page.locator('#qa-status').selectOption('resolved');assert.equal(await page.locator('.qa-item').count(),1);
 await page.locator('#qa-edit').click();await page.locator('#qa-tags').fill('점화 시점, 복습');await page.locator('#qa-compose button[type=submit]').click();assert.equal(await page.locator('.qa-answer').count(),1);
 await page.locator('[data-filter-tag="복습"]').click();assert.equal(await page.locator('.qa-item').count(),1);await page.screenshot({path:'artifacts/questions-desktop.png'});
 const download=page.waitForEvent('download');await page.locator('#qa-export').click();await(await download).saveAs('/tmp/auto-atlas-questions-test.json');
 const link=await page.locator('#qa-thread a').first().getAttribute('href');await page.goto('http://127.0.0.1:5173'+link);await page.waitForFunction(()=>window.__mechanics);assert.equal(await page.evaluate(()=>window.__mechanics.getState().selected),'plug-0');
 await page.locator('#qa-open').click();await page.locator('#qa-current').check();assert.equal(await page.locator('.qa-item').count(),1);await page.locator('.qa-item').click();assert.equal(await page.locator('.qa-answer').count(),1);
 await page.locator('#qa-close').click();await page.locator('[data-system="suspension"]').click();await page.locator('#qa-open').click();assert.equal(await page.locator('.qa-item').count(),0);await page.locator('#qa-current').uncheck();assert.equal(await page.locator('.qa-item').count(),1);
 await page.setViewportSize({width:390,height:844});await page.locator('.qa-item').click();await page.screenshot({path:'artifacts/questions-mobile.png',fullPage:true});assert(!await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth));assert(!await page.locator('#qa-board').evaluate(e=>e.scrollWidth>e.clientWidth));
 await page.locator('#qa-close').click();await page.goto('http://127.0.0.1:5173/');await page.waitForFunction(()=>window.__atlas);await page.locator('#qa-open').click();assert.equal(await page.locator('.qa-item').count(),1);await page.locator('.qa-item').click();await page.locator('#qa-delete').click();await page.locator('#qa-delete-no').click();assert.equal(await page.locator('.qa-item').count(),1);await page.locator('#qa-delete').click();await page.locator('#qa-delete-yes').click();assert.equal(await page.locator('.qa-item').count(),0);
 await page.locator('#qa-new').click();await page.locator('#qa-title').fill('작성 보존');await page.locator('#qa-close').click();await page.locator('#qa-open').click();assert.equal(await page.locator('#qa-title').inputValue(),'작성 보존');
}
